! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:56:05 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=80; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.592327       -0.413838      3.20184e-06    -1.19939e-05         0.150765       -0.674301     -2.77845e-05     -3.8978e-05
                     2.53413e-05    -1.89158e-05       -0.0815662       -0.264726       -7.195e-05    -6.36751e-05         0.909311        0.310326
                        0.150688       -0.674412     -0.000136398    -9.85318e-05        -0.711805        0.122924      -1.1591e-05     0.000103515
                     7.99312e-07    -7.00904e-05         0.909473        0.310154     -9.20848e-05     4.76281e-05          0.22632       -0.159759
281800                 -0.595187        -0.41305      2.89638e-06    -1.18681e-05         0.142542       -0.674037      -2.6844e-05    -3.86654e-05
                     2.50386e-05     -1.8683e-05       -0.0833518       -0.263173     -7.08105e-05    -6.20295e-05          0.91162        0.304337
                        0.142496        -0.67416     -0.000138571    -9.75639e-05         -0.71107        0.137442      -8.3259e-06     0.000102949
                     4.50441e-07    -6.96603e-05         0.911781        0.304166     -8.91233e-05     5.02291e-05         0.224664       -0.160451
[End]