! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:58 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=150; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.266232       -0.556156     -1.27704e-05     0.000395137         0.598186       -0.511586      0.000178517    -7.80113e-05
                     0.000105038     0.000430029       -0.0541002        -0.36439      0.000160273    -0.000159823         0.918937        0.139413
                         0.59805       -0.511689      0.000198242    -0.000147848        -0.508095       -0.349018      0.000230085     0.000269557
                     0.000278018     -7.5118e-05         0.918873        0.139103      0.000212292     0.000303472          0.15981        -0.33201
281800                 -0.268067       -0.556294     -8.72947e-06      0.00039711         0.591524       -0.518181        0.0001783    -7.79983e-05
                     0.000102231       0.0004284       -0.0562815       -0.362649      0.000159982    -0.000161406         0.920678        0.131388
                        0.591399       -0.518278      0.000199866    -0.000151167         -0.51614       -0.338679      0.000232263     0.000269401
                     0.000276341    -7.73892e-05         0.920609        0.131084      0.000215554     0.000303623         0.155541       -0.332489
[End]