! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:12:55 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=200; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.290361       -0.175153      4.23785e-05     0.000139684         0.319579        0.884824     -1.21488e-05    -6.26209e-05
                     5.60673e-05     0.000131103        -0.337308       -0.181743      5.64033e-05     0.000100853         0.354542        0.852906
                        0.319609        0.884603       7.4535e-05     0.000112878        -0.111381        0.320307     -2.14505e-05     -7.1396e-05
                     7.40339e-05     1.25121e-05         0.354549        0.852903     -7.26747e-06    -9.44708e-05           -0.109        0.367317
281800                 -0.291994       -0.175796      4.36373e-05     0.000139731         0.325673        0.881932     -1.20195e-05    -6.18506e-05
                     5.89415e-05     0.000132089        -0.339049       -0.182106      5.74344e-05      0.00010121         0.360353        0.849697
                          0.3257        0.881712      7.51151e-05     0.000113026         -0.10762        0.323414     -2.21331e-05    -7.21701e-05
                     7.59812e-05     1.60971e-05         0.360361        0.849693     -8.21145e-06    -9.53382e-05        -0.104687        0.370342
[End]