! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:10 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=180; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.673021       -0.401376     -0.000553056     -0.00134234         0.410829         0.46538      0.000265424    -0.000274691
                    -0.000541727     -0.00129947          0.67575       -0.300324      6.64317e-05    -0.000557212         0.392154        0.546573
                        0.410661        0.465284      5.72164e-05    -0.000457548         0.482076       -0.617917      0.000646283     0.000200363
                     0.000383359    -0.000257468         0.392081        0.546682      0.000555335     0.000240548         0.501231       -0.543927
281800                  0.669401       -0.405655      -0.00056096     -0.00133114         0.415762          0.4625       0.00029929    -0.000333003
                    -0.000549762     -0.00128733         0.672432       -0.304875      5.97669e-05    -0.000556905         0.397823        0.544071
                        0.415592        0.462405      4.95676e-05     -0.00045599          0.47473        -0.62245       0.00055396     0.000226546
                     0.000379171    -0.000260017          0.39771        0.544193      0.000562285     0.000234561         0.494737       -0.548212
[End]