! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:59:27 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=110; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0248752       0.0750576      0.000171018    -0.000242339         0.281432       -0.956252     -0.000227233     3.05858e-07
                     0.000409441    -0.000138282       -0.0295861      -0.0209385     -0.000259186     5.61735e-06        0.0635959       -0.997151
                        0.281407       -0.956203     -0.000297196     6.01973e-05        0.0197919      -0.0765324      0.000124872     0.000213333
                    -0.000268378    -0.000157637        0.0636334       -0.997217      0.000123849     0.000239276       -0.0319266       0.0170508
281800                -0.0234553       0.0732649      0.000168598    -0.000244845         0.273999       -0.958583      -0.00022469     3.72684e-07
                     0.000495007    -0.000229015       -0.0294495      -0.0232314     -0.000259946     8.88897e-06        0.0553356       -0.997593
                        0.273954       -0.958534     -0.000296762     6.37723e-05        0.0188347      -0.0745564      0.000133045     0.000213648
                    -0.000322671    -0.000195764         0.055369       -0.997661      0.000127936     0.000239515       -0.0317563       0.0198716
[End]