! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:55:54 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=80; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.918966        0.226411     -0.000272746    -0.000101285        -0.277069       -0.164284     -0.000300317     0.000191098
                    -0.000241663    -7.64862e-05        -0.250705      -0.0580658     -0.000495157     0.000135177         0.906884       -0.333735
                       -0.277073       -0.164293     -0.000512446     0.000218862         0.243183        0.914666      0.000117194     0.000531494
                    -0.000374141     0.000173284         0.906773       -0.333862     -8.28423e-05     0.000495494         0.153218       -0.206767
281800                 -0.918483        0.231427     -0.000273614    -9.85286e-05        -0.276684       -0.160601     -0.000295894     0.000193465
                    -0.000242218    -7.50588e-05        -0.249675       -0.055995     -0.000493827     0.000141478         0.904893       -0.340207
                       -0.276688       -0.160609     -0.000508124     0.000226611         0.255544        0.912065      0.000125209      0.00052545
                    -0.000372268     0.000176948         0.904778       -0.340333     -7.72298e-05     0.000496395           0.1509       -0.206654
[End]