! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:11:18 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=190; L_y=160; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.242463        0.224261      0.000350425     0.000321408         0.788227       -0.519056     -0.000164535    -2.90587e-05
                     0.000283665     0.000276437        -0.113575         0.17425     -8.57698e-06    -0.000161778         0.593976       -0.776881
                        0.788102       -0.519012     -1.05108e-05    -0.000102743         0.301827       -0.133806      0.000210711     0.000250986
                     -0.00018419     4.71288e-06         0.593791       -0.776883      0.000225582     0.000229407         0.138416       -0.155118
281800                  -0.23914        0.224841      0.000382673     0.000323825         0.784093       -0.526558     -0.000171231    -2.56117e-05
                     0.000285735     0.000273449        -0.110796        0.172991     -9.45737e-06    -0.000161944         0.587337       -0.782585
                         0.78396       -0.526524      2.24261e-05    -7.39025e-05         0.298633       -0.135957      0.000208453     0.000260579
                    -0.000184555     4.53703e-06          0.58719       -0.782732       0.00022685     0.000231354         0.135213       -0.154557
[End]