! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:53 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=140; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                0.00394968       0.0394683      0.000697576     0.000567059       -0.0930508         0.99492     -0.000788267    -0.000209847
                     0.000554479     0.000744584       -0.0102313        0.017684     -0.000790207    -2.10996e-05       -0.0665683        0.997576
                      -0.0930387        0.994755     -0.000749456     0.000130868        0.0111637      -0.0380685      0.000650176    -0.000625695
                    -0.000783695    -0.000171193       -0.0664141        0.997602      0.000676497    -0.000629872       -0.0077997      -0.0188709
281800                0.00435721       0.0375557       0.00069689      0.00056211       -0.0863226        0.995599     -0.000792353    -0.000204033
                     0.000556076     0.000741013      -0.00998175       0.0157787     -0.000794505    -1.43629e-05       -0.0597697        0.998039
                      -0.0863116        0.995432     -0.000747541     0.000139262         0.010719      -0.0362618      0.000643564    -0.000633704
                    -0.000785404    -0.000165716       -0.0596175        0.998068      0.000667577    -0.000638839      -0.00803411      -0.0168414
[End]