! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:29 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=160; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.206747        -0.19189      0.000852501     0.000766557        -0.923007       -0.260554      0.000246532     0.000490766
                     0.000859027     0.000755014        -0.145788       -0.245489     -0.000184122    -0.000498289         0.916356        0.279566
                       -0.923159       -0.260852     -0.000250264    -0.000487103         0.276599      -0.0553844       0.00107005    -0.000502296
                     0.000346401      0.00061571         0.916279        0.279569       0.00102209    -0.000452931         0.258068       -0.122356
281800                 -0.208834       -0.189348      0.000858725     0.000762517        -0.925289       -0.252505      0.000249679     0.000488457
                     0.000801334     0.000768098        -0.148342       -0.243342      -0.00018841    -0.000493816         0.919139        0.270817
                       -0.925429       -0.252668     -0.000255513    -0.000484041         0.276109      -0.0569887       0.00106639    -0.000515362
                     0.000349313     0.000463821         0.919053        0.270815       0.00101676    -0.000465547          0.25666       -0.124087
[End]