! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:25 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=140; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0475016       -0.268459      0.000348472     0.000236881         0.873164        0.404153      3.75815e-05     7.22614e-05
                     0.000374948     0.000188293        -0.178696       -0.251451      0.000139443      0.00011217         0.950982       -0.024491
                        0.873163        0.404316      0.000135861     9.13167e-05          0.23545       -0.137417     -0.000402636     5.92689e-05
                     3.95588e-05     8.63951e-05         0.950861      -0.0246389      -0.00038022      9.8419e-05         0.165444        -0.26027
281800                -0.0495833       -0.267235      0.000350617     0.000234608         0.876027        0.398482      3.88625e-05     7.14191e-05
                     0.000376673     0.000186135        -0.179263       -0.249464      0.000140278     0.000110017         0.951194      -0.0313891
                        0.876027        0.398645      0.000136568      8.9876e-05         0.234061       -0.138137     -0.000403115     6.13578e-05
                     4.02709e-05      8.5358e-05         0.951077      -0.0315372     -0.000380828     0.000101378         0.162355       -0.260693
[End]