! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:19 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=140; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.904632        0.352558      0.000168914     0.000875866         0.208419        0.116938      0.000491782     0.000182925
                     0.000183272     0.000860904        -0.994794      -0.0558843      7.21899e-05     2.97977e-05        0.0433121       0.0706628
                        0.207983        0.117193      0.000197222    -3.57563e-06         0.170104        0.955825       0.00161749     0.000302995
                     0.000442841     8.10638e-05        0.0431152       0.0707847      0.000970211     0.000579393        -0.404818        0.910293
281800                 -0.903119        0.356174      0.000172639     0.000875614         0.209684        0.115383      0.000493428     0.000175079
                      0.00018554     0.000862521        -0.994904       -0.051346      7.41474e-05     3.31482e-05        0.0448927       0.0715908
                        0.209275        0.115613      0.000199246    -1.17371e-05         0.182005        0.953544       0.00162246      0.00027464
                     0.000447022     9.19132e-05        0.0446972       0.0717055       0.00098627     0.000582312        -0.390201        0.916509
[End]