! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:00 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=180; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.181642        0.203712     -2.90341e-05     0.000434745         0.715117       -0.643298     -0.000212989     4.43368e-05
                    -2.56224e-05     0.000351207         -0.14232        0.186806     -0.000131568    -3.91828e-06         0.649791        -0.72284
                        0.715132       -0.643003     -0.000145215     0.000116263         0.221834       -0.158779      0.000221928    -3.13745e-05
                    -0.000152688     2.45305e-05         0.649654        -0.72267      0.000287312    -5.56296e-05         0.170667       -0.161192
281800                   -0.1785        0.203609     -2.71778e-05     0.000433944         0.709848       -0.649974     -0.000212162     4.59536e-05
                    -2.35993e-05     0.000352683        -0.139354          0.1861     -0.000107568    -1.27099e-05         0.643741       -0.728983
                         0.70987       -0.649715     -0.000142269     0.000116602         0.218622       -0.159559        0.0002235    -3.55496e-05
                    -0.000150791     2.72878e-05         0.643604       -0.728814      0.000336631    -8.17796e-05         0.167453       -0.161157
[End]