! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:56:22 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=90; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0576299        0.219544     -0.000403669     0.000108999        -0.299892        0.926496      3.32793e-05     6.66741e-05
                    -0.000443873     0.000106893        0.0561051        0.208873      5.60949e-05    -9.78473e-05        -0.290252        0.932127
                       -0.299727        0.926512      6.39286e-05     -3.2928e-05         0.175321       -0.144189     -0.000307557    -0.000328103
                    -8.68464e-07      9.2502e-05        -0.290188        0.932145     -0.000235581    -0.000325985         0.164787       -0.140133
281800                 0.0591828        0.217958     -0.000403341     0.000111901        -0.294052        0.928643      3.40491e-05      6.6344e-05
                    -0.000444677     0.000111048        0.0576028        0.207258      5.58366e-05    -9.81388e-05         -0.28435        0.934214
                       -0.293885        0.928659      6.41447e-05    -3.31624e-05         0.173823       -0.144225      -0.00031071    -0.000326932
                    -1.17915e-06      9.1968e-05        -0.284284         0.93423     -0.000238468    -0.000325108         0.163322       -0.140057
[End]