! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:55 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=160; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.132561        -0.30233      0.000136796     2.23805e-05         0.887661        0.321034      0.000142845     -0.00026569
                     0.000113195    -4.48827e-05         -0.18013       -0.292302      0.000132232    -0.000272043         0.906848        0.244131
                        0.887672        0.321139     -4.46606e-06    -0.000244898         0.295181       -0.147591     -0.000160304    -0.000289819
                     8.71181e-05    -0.000189696         0.906986        0.244533     -0.000192366    -0.000276749         0.302417       -0.162372
281800                 -0.134451       -0.301053       0.00014028     1.78808e-05         0.890048        0.314776      0.000139695    -0.000266826
                     0.000115766    -4.52472e-05        -0.181773       -0.290772      0.000127707    -0.000273538         0.908731        0.237651
                         0.89006        0.314878      -3.2918e-06    -0.000246968         0.293724       -0.149584     -0.000164862    -0.000291217
                     8.71035e-05    -0.000192172         0.908864        0.238051     -0.000196011    -0.000278594         0.300738       -0.164562
[End]