! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:09:39 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=180; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.989692       0.0391827     -0.000333411     -0.00089122        0.0841779        0.107225     -0.000343559    -3.66843e-05
                    -0.000365906    -0.000840194        -0.837254        0.489008     -0.000500962    -0.000231543         0.230053       0.0820445
                       0.0841523        0.107233     -0.000340838    -0.000167716        -0.275006        0.951466     -0.000498871     0.000294245
                    -0.000401096    -7.89051e-05         0.229948       0.0819175     -0.000617585     7.37716e-05         0.338559        0.908543
281800                  -0.98935        0.043466     -0.000338729    -0.000890341        0.0859803         0.10735     -0.000340341    -3.43306e-05
                    -0.000274022    -0.000919175        -0.835257        0.492337     -0.000504039    -0.000225989         0.230824        0.080304
                        0.085989        0.107431      -0.00034528    -0.000154556        -0.260532        0.955357      -0.00048487     0.000298644
                    -0.000420772    -5.38169e-05          0.23072       0.0801873     -0.000614457     8.29151e-05         0.348997        0.904545
[End]