! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:14 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=160; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.063174       -0.266167     -0.000164718     0.000183998         0.889025        0.367432       0.00030164      3.8051e-05
                    -0.000216592     0.000210075        -0.233397       -0.307996     -0.000131738    -7.95993e-06         0.836988       -0.387106
                        0.888884        0.367534     -0.000150261      6.4403e-07         0.232641       -0.143867      0.000214816     0.000296931
                     0.000217436     5.65472e-05          0.83719       -0.387017      0.000250596     0.000228368       -0.0835845       -0.377084
281800                -0.0651425       -0.264796     -0.000162092     0.000186131         0.891668        0.361629      0.000303997     3.43171e-05
                    -0.000214249     0.000212728        -0.233178       -0.307015     -0.000131518    -7.13649e-06         0.833995       -0.394402
                        0.891528         0.36173     -0.000149845     1.95948e-06         0.231172       -0.144582       0.00021698     0.000297011
                     0.000219043     5.38978e-05         0.834198       -0.394312      0.000252296     0.000228242       -0.0893942       -0.374808
[End]