! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:01:36 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=120; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.25977       -0.208201     -0.000935009     0.000721713         0.913758         0.23282      0.000512157    -0.000338599
                    -0.000626886     0.000498859        0.0167244       -0.247471     -0.000127976    -0.000348557         0.745232        0.619239
                          0.9136        0.232487      0.000102906    -0.000537936         0.327668      -0.0585492     -2.13918e-05     0.000570895
                     0.000573236     -0.00030253         0.745288        0.619228      1.56801e-05     0.000564612         0.240168      -0.0618101
281800                 -0.261148       -0.206281     -0.000934205     0.000731663         0.915408        0.226416      0.000507337    -0.000340517
                    -0.000628079     0.000504675        0.0143624       -0.247378     -0.000131826    -0.000349779         0.749449        0.614227
                        0.915231        0.226078      0.000101144    -0.000539167         0.327138      -0.0607967     -1.66541e-05     0.000572462
                     0.000570287    -0.000309201         0.749506        0.614218      1.97494e-05     0.000566758         0.239684      -0.0627171
[End]