! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:37 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=160; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0312045       -0.228448      0.000359868      2.0779e-05         0.706056        0.669588     -0.000534636     0.000651728
                     0.000388762    -6.98923e-05        -0.147915       -0.240249     -0.000203676     0.000646257         0.848418        0.447768
                        0.706338        0.669287     -0.000278811     0.000660625         0.226445      -0.0434515     -9.24596e-05    -1.45626e-05
                    -0.000482168     0.000532554         0.848402        0.447749     -0.000111101     0.000269662         0.281763      -0.0134847
281800                 0.0288495       -0.228584      0.000357554     1.88852e-05         0.710569        0.664861     -0.000535852     0.000654047
                     0.000384382    -7.18915e-05        -0.149999       -0.239079     -0.000197786     0.000650101          0.85144        0.441928
                        0.710848        0.664555      -0.00027469       0.0006635         0.226136      -0.0441499     -9.08641e-05     -9.4803e-06
                    -0.000479237     0.000536368         0.851426        0.441904     -0.000106213     0.000274133         0.281795      -0.0149687
[End]