! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:55:21 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=80; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0446461        0.150852      0.000198808     0.000120121        -0.228322         0.96081      3.14665e-05    -3.65846e-06
                     0.000282994     0.000108288        0.0557753        0.203232      4.67858e-05     -6.1824e-05        -0.280519        0.936457
                       -0.228238        0.960664      7.88888e-06    -6.64014e-05         0.107711       -0.114625      0.000212334     2.81048e-06
                     8.98583e-08     4.57691e-05        -0.280478        0.936386      0.000202011    -8.80167e-06         0.158297       -0.139077
281800                 0.0458208        0.149082      0.000200014     0.000119579        -0.222084        0.962492      3.14386e-05    -3.93028e-06
                     0.000283584     0.000108385        0.0572396        0.201591      4.63335e-05    -6.23567e-05        -0.274572        0.938484
                       -0.221999        0.962345      6.78163e-06    -6.64744e-05         0.106483       -0.113918      0.000212488     1.56392e-06
                    -1.46536e-06      4.4896e-05         -0.27453        0.938411       0.00020171    -1.00126e-05         0.156846       -0.138927
[End]