! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:09:14 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=180; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0996616       -0.179078      0.000165237    -7.99429e-05         0.595643        0.777099      0.000101194     3.78063e-05
                     0.000171474    -0.000156299        -0.236122       -0.191244      3.54018e-05     7.30025e-05         0.865938        0.397511
                        0.595409        0.776861      -7.9455e-05    -9.27434e-05         0.198796      -0.0497084      5.64182e-05    -0.000165786
                     9.37031e-05    -1.28749e-05         0.865874        0.397472      0.000106349     1.06156e-06         0.298905       0.0543649
281800                 0.0974686       -0.179894      0.000167843    -7.95179e-05         0.600823        0.773191      0.000102424     3.91008e-05
                      0.00017275    -0.000157676        -0.237976       -0.189614      3.54346e-05     7.11331e-05         0.868499        0.391556
                        0.600592        0.772951     -8.02785e-05     -9.2772e-05         0.198368      -0.0500149      5.32496e-05    -0.000168092
                     9.41473e-05    -1.27304e-05         0.868437        0.391516      0.000106085    -2.92084e-06         0.299623       0.0527609
[End]