! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:12:02 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=200; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0880567       -0.191954     -0.000414708     9.55718e-05         0.625174        0.751368      0.000188049    -0.000332826
                    -0.000413734      0.00013018        -0.337772       -0.112706      0.000447211    -0.000473691         0.910049        0.212249
                        0.625307        0.751394      0.000450191    -0.000380329         0.204697      -0.0517305     -3.52486e-05     0.000250167
                     2.86254e-05    -0.000503783         0.909954        0.212165      0.000161805     0.000165373         0.352718       0.0483491
281800                 0.0858091        -0.19261        -0.000413     9.74256e-05          0.63021        0.747247      0.000187893    -0.000336164
                    -0.000412088     0.000127173        -0.338815       -0.110416      0.000438889      -0.0004776         0.911377        0.205994
                        0.630333        0.747275      0.000447151     -0.00038346         0.204259      -0.0521199     -3.14306e-05     0.000249807
                     2.58271e-05    -0.000505377         0.911282        0.205911      0.000164089     0.000158674         0.353303        0.046034
[End]