! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:29 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=170; L_y=160; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.416964        0.307109     -0.000356477      0.00047505         0.828101       -0.213169     -0.000270739    -3.86597e-06
                    -0.000376081     0.000491217        -0.301157        0.290282     -0.000420075    -4.12551e-05         0.814785       -0.400994
                        0.828037       -0.212856     -0.000290894     5.78452e-05         0.512998       0.0687375      0.000759103     0.000135561
                    -0.000335935     2.10852e-05         0.814804       -0.400886      0.000581489    -1.15469e-05         0.413616      -0.0609578
281800                 -0.412156        0.308481     -0.000348807     0.000483751         0.827451       -0.222858     -0.000265478    -4.54499e-06
                    -0.000368166     0.000498796         -0.29738        0.291084      -0.00042115     -3.4386e-05         0.811826        -0.40915
                        0.827393       -0.222539     -0.000288504     6.28841e-05          0.51093       0.0608871      0.000768033     0.000131543
                    -0.000332834     2.32684e-05         0.811847       -0.409042      0.000579294      -1.126e-05          0.41078      -0.0652833
[End]