! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:39 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=170; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.690582        0.682008      -0.00121721     -0.00125429         0.239093       0.0215947      9.64234e-05     0.000182401
                     -0.00116892     -0.00120859        -0.737928        0.627309      -0.00032348     8.52917e-05         0.245042       0.0407823
                        0.239312       0.0215249     -0.000171283      1.2758e-05         0.556924        0.794913      0.000274948    -0.000144657
                      0.00017151     0.000152851         0.244995       0.0407058      0.000103481    -0.000209725          0.49497        0.832471
281800                 -0.687768        0.684917      -0.00121934     -0.00125453         0.239041       0.0198286      9.83483e-05     0.000181334
                      -0.0011736     -0.00120473        -0.735341         0.63044     -0.000323275     8.73742e-05          0.24509       0.0388977
                        0.239269       0.0197511     -0.000175399     2.11835e-05         0.565264        0.789064      0.000273056    -0.000148514
                     0.000171199       0.0001487          0.24505       0.0388068      0.000102482    -0.000214602         0.504008        0.827107
[End]