! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:14 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=130; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.217582      -0.0728474     -0.000153387     -0.00029184         0.796156       -0.559857     -0.000394741    -0.000247036
                    -0.000102379    -0.000411614        -0.400373       -0.315465     -0.000473977    -2.36626e-05         0.124697       -0.851112
                        0.796135       -0.559785     -0.000470983    -4.25938e-05       0.00503169       -0.229338      -0.00038122     0.000295098
                    -0.000364459    -0.000197504         0.124769        -0.85112     -0.000438317     0.000307947         -0.47378        0.187603
281800                 -0.215987      -0.0717692     -0.000154209    -0.000294911         0.792198       -0.566192     -0.000400318    -0.000244407
                    -0.000104638    -0.000414817         -0.40223       -0.316238     -0.000476502    -1.90525e-05         0.115672       -0.851224
                        0.792176       -0.566118     -0.000473348     -3.7659e-05       0.00202114        -0.22753     -0.000377858     0.000302219
                    -0.000368182    -0.000193146         0.115742       -0.851231     -0.000435137     0.000316342        -0.471768        0.197682
[End]