! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:28 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=160; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.104959       -0.137282      0.000133489     -0.00038309         -0.30473       -0.936539      0.000167466     0.000480308
                     0.000200329    -0.000511639         0.552093        0.443658     -0.000499157      0.00026117       -0.0844127        0.700072
                       -0.304655       -0.936484     -0.000408711     0.000234307       -0.0039633        0.172746      9.74128e-05    -0.000594813
                     0.000116706     0.000539385        -0.084508        0.700193      6.05137e-05    -0.000528033         0.642256       -0.299116
281800                 -0.106992       -0.138973      0.000132591     -0.00038542        -0.312848       -0.933378      0.000180632      0.00047645
                     0.000195334    -0.000513211         0.555428        0.437589     -0.000503095     0.000269812        -0.077705        0.702029
                       -0.312766       -0.933324     -0.000405881     0.000236535      -0.00151422        0.175366       9.0937e-05    -0.000595037
                     0.000124323     0.000536437       -0.0778011        0.702149      5.27533e-05    -0.000526794         0.638221       -0.304927
[End]