! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:54:09 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=70; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0341082        0.117417     -8.17309e-05    -0.000132862        -0.195873        0.973194      2.62207e-05     6.56208e-05
                    -0.000133827    -0.000172684        0.0563892        0.209483      7.16385e-05    -2.07327e-05        -0.288772        0.932353
                       -0.195775        0.972948      9.15267e-05    -1.14794e-05        0.0768877      -0.0950817     -0.000162686     1.47212e-05
                     6.41937e-05     8.35771e-05        -0.289064        0.932434     -0.000168288     3.60422e-05         0.165013       -0.140829
281800                 0.0350812         0.11559     -8.28801e-05    -0.000132765        -0.189472        0.974645      2.66343e-05     6.72276e-05
                     -0.00013593    -0.000172948        0.0578864        0.207868      7.12251e-05    -2.05066e-05        -0.282869        0.934426
                       -0.189374        0.974396      9.13638e-05     -1.1807e-05        0.0758425       -0.094031     -0.000162487     1.61946e-05
                     6.52114e-05     8.33089e-05         -0.28316        0.934512     -0.000167637     3.73785e-05         0.163544       -0.140757
[End]