! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:56:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=90; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0869483       -0.108107      3.01614e-06    -0.000499938        -0.150236       -0.978765     -0.000420456    -0.000111127
                     4.67281e-05    -0.000551203       -0.0616764        0.142925     -0.000433693    -9.67804e-05         0.456062       -0.875994
                       -0.150253       -0.978756     -0.000387132    -9.68598e-05       -0.0504008        0.129268     -6.96514e-05     0.000465939
                     -0.00034555    -6.89401e-05         0.456046       -0.876214     -0.000132789     0.000521004        0.0816772       -0.132524
281800                -0.0882463        -0.11022     -1.19242e-06    -0.000499244        -0.158697       -0.977075     -0.000421541    -0.000105419
                     4.14551e-05     -0.00054975       -0.0595229        0.141924     -0.000434801    -9.21327e-05         0.449671       -0.879604
                       -0.158718       -0.977068      -0.00038932    -9.40115e-05       -0.0487035        0.132544     -6.19436e-05     0.000464993
                    -0.000345385    -6.65058e-05         0.449656       -0.879822     -0.000125733     0.000521354          0.08015        -0.13139
[End]