! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:01:39 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=120; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0359625       -0.442738      9.66485e-05     -0.00115835         0.871532        0.206396        0.0011363    -0.000165041
                     0.000107943    -0.000850512         0.194394        0.583834       0.00112513    -0.000824058        -0.372016         0.69431
                        0.871789        0.206212       0.00120168     -0.00080863         0.166486       -0.411923      -0.00043192    -0.000278274
                      0.00115469     -0.00030283        -0.372274        0.694326     -0.000273591    -0.000394812         0.594055       -0.161168
281800                 0.0327987       -0.441558      8.76439e-05     -0.00116497         0.874112        0.198398       0.00113318    -0.000163056
                     0.000101479    -0.000854629          0.20013        0.580848       0.00111442    -0.000835202        -0.365371        0.698694
                        0.874365        0.198217       0.00119453     -0.00082101         0.161105       -0.412531     -0.000445151    -0.000267337
                      0.00115049    -0.000315208        -0.365631        0.698709      -0.00027184    -0.000385201         0.591514       -0.166655
[End]