! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:17 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=160; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.162916       -0.018581      7.29899e-05    -0.000172731        -0.244234       -0.955643      0.000166442     0.000445282
                    -0.000198647      -0.0001617         0.229201       0.0472037      1.06761e-05     0.000391604          0.14104        0.961736
                       -0.244111       -0.955858     -4.57171e-05     0.000278472         0.151912      -0.0617917     -2.08065e-05    -0.000180561
                     8.76473e-05     0.000384143         0.140836        0.961467      4.78386e-05    -5.82086e-05         0.206242       -0.111067
281800                  0.162027      -0.0210104      6.55943e-05    -0.000175451        -0.251369       -0.953895      0.000169078     0.000446104
                    -0.000191081     -0.00015755         0.228939       0.0424399      1.33736e-05     0.000390163         0.151564        0.960415
                       -0.251249       -0.954109     -4.10273e-05      0.00028276         0.151397      -0.0614953     -2.25508e-05    -0.000181843
                      8.9316e-05     0.000383647         0.151363        0.960152      4.66821e-05    -5.72464e-05         0.204987       -0.110922
[End]