! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:09:55 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=180; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.165402       -0.130408     -5.68544e-05     -4.7967e-06          0.18273        0.960269      0.000244995    -2.35415e-07
                    -8.26544e-05    -5.35139e-06        -0.201217        -0.14753      0.000269692    -0.000124446         0.219597         0.94323
                        0.182823        0.960227      0.000424421    -8.20127e-05        -0.105933         0.18208      0.000144671     0.000108753
                     0.000221845     9.83663e-05         0.219404        0.943158      0.000127349     0.000213444        -0.115279        0.221287
281800                 -0.166476       -0.131757      -5.6018e-05    -3.38185e-06         0.189452        0.958593      0.000243506    -2.36252e-06
                     -8.2574e-05    -4.73932e-06        -0.202472       -0.148701      0.000269378     -0.00013033         0.226197        0.941214
                        0.189547         0.95855      0.000425464    -8.35881e-05        -0.103825         0.18522      0.000146939     0.000105577
                     0.000221453     9.89545e-05         0.226004        0.941143      0.000134506     0.000212817        -0.112704         0.22452
[End]