! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:58:12 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=100; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.137482       -0.273586     -8.34084e-05    -0.000145071         0.948264        0.084118      1.65585e-05    -0.000148539
                    -9.76273e-05    -0.000152161       -0.0966575       -0.269272     -5.50041e-05    -0.000171437         0.923835          0.2549
                        0.948243       0.0841246     -6.62912e-05    -0.000189461         0.183475       -0.245004      4.36117e-05    -0.000162668
                     2.59183e-05    -0.000168225         0.923751        0.254804      8.03062e-05    -0.000178071         0.220997       -0.181614
281800                 -0.138502       -0.271692     -8.43112e-05    -0.000145662         0.949227       0.0774417      1.62273e-05    -0.000148956
                    -9.84214e-05    -0.000153078       -0.0982771       -0.267596     -5.64762e-05    -0.000170822         0.925834        0.248717
                        0.949208       0.0774469      -6.7672e-05    -0.000188759          0.18069        -0.24554      4.34941e-05    -0.000164442
                     2.46487e-05    -0.000168208         0.925749        0.248623      7.97317e-05    -0.000179507         0.219078       -0.182326
[End]