! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:05 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=140; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0445577      -0.0284787     -2.81365e-05     0.000199245      -0.00284976        0.998849      9.43797e-05     6.84317e-06
                      7.0341e-05     0.000256698       -0.0245127     -0.00412927      3.36262e-05     0.000369158       -0.0365486        0.999099
                     -0.00286675        0.998637      6.08344e-05      8.4238e-05       -0.0447631       0.0282302      -0.00018398    -0.000183055
                     2.74681e-05    -7.82396e-05       -0.0364358        0.998984     -1.67405e-05    -0.000247972       -0.0247387      0.00232639
281800                 -0.044666      -0.0303292     -2.58204e-05     0.000195811       0.00404933        0.998784      9.14168e-05     2.57605e-06
                      7.2526e-05     0.000256531       -0.0244276     -0.00601429      3.49674e-05     0.000365099       -0.0297027        0.999316
                      0.00403323        0.998571      6.10341e-05     8.51642e-05       -0.0444612       0.0306976     -0.000184495    -0.000182262
                     2.72141e-05    -7.82976e-05        -0.029591        0.999204     -2.02899e-05     -0.00024923       -0.0247297      0.00455182
[End]