! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:59:32 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=110; L_y=110; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.211068      -0.0967749     -0.000436265     4.09213e-05         0.733141       -0.638954     -1.22771e-05     0.000210922
                    -0.000404458     1.46836e-05        -0.212002      -0.0964731      6.64857e-05     0.000152247         0.733548       -0.638328
                        0.733246          -0.639      4.76242e-05     0.000127744       -0.0669858       -0.222218      0.000209019    -0.000373465
                    -6.07417e-06     0.000227932         0.733591       -0.638294      0.000193612    -0.000380793       -0.0662194       -0.223214
281800                 -0.209477      -0.0962237     -0.000434706     4.31042e-05           0.7283       -0.645067     -9.77476e-06     0.000211304
                    -0.000403329     1.59873e-05        -0.210414      -0.0959127       6.8313e-05     0.000151365         0.728716       -0.644442
                        0.728405       -0.645112      4.88444e-05     0.000126528       -0.0701804       -0.219471      0.000201882    -0.000375368
                    -3.78405e-06     0.000227856         0.728759       -0.644408      0.000187736    -0.000382066       -0.0694217        -0.22048
[End]