! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:14 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=150; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.222658       -0.469565     -0.000358731     8.41458e-05         0.759561        -0.39085     -0.000492995     0.000491236
                    -0.000344747     -0.00019361        -0.823324       -0.451998     -0.000242063    -6.13249e-05        0.0143276       -0.342149
                        0.759695       -0.390827     -0.000207517    -7.29097e-05        -0.252857       -0.453816      -0.00053975      0.00018406
                    -0.000664682     0.000353829        0.0143226       -0.342005     -0.000388345      0.00032073        -0.857374        0.383078
281800                 -0.223334        -0.46904       -0.0003579     8.75818e-05         0.756033       -0.397864     -0.000488033     0.000497557
                     -0.00035347    -0.000190045        -0.826507       -0.448444     -0.000242603    -5.87328e-05        0.0100798       -0.339289
                        0.756167       -0.397847      -0.00020916    -7.17676e-05        -0.260339       -0.449351     -0.000534341     0.000194323
                    -0.000663368     0.000365802        0.0100717       -0.339148     -0.000379246     0.000326935        -0.850778        0.400086
[End]