! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:17 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=150; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.101172        -0.01094      0.000608059     0.000422445         0.146345        0.983775     -0.000210941    -0.000273791
                      0.00057827     0.000371071        -0.206556       -0.196383      0.000485922     0.000375082         0.953169       0.0973021
                        0.146303        0.983576      0.000369243      0.00029708         0.100228      -0.0190712     -0.000326437    -0.000595121
                    -0.000182621    -0.000365948         0.953403       0.0970812     -0.000357221    -0.000426051         0.241958       -0.150742
281800                  0.100638      -0.0148494      0.000610852     0.000414685          0.15732        0.982153     -0.000211581     -0.00026994
                     0.000578604     0.000365674        -0.207885       -0.193753      0.000460224      0.00032716         0.954297       0.0884721
                        0.157297        0.981879      0.000371118      0.00029351         0.100485      -0.0174076     -0.000335489    -0.000585649
                    -0.000187252    -0.000363999         0.954507       0.0882288     -0.000341682    -0.000471951         0.239934       -0.152389
[End]