! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:58:44 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=100; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.612375     -0.00659128     -0.000466979    -0.000946299         0.269137        0.742556      -0.00065209       0.0004324
                    -0.000510117     -0.00105259        -0.160983       -0.164563      0.000193837     0.000170714        -0.427387       -0.874042
                        0.268999         0.74282      0.000195141     0.000126711         0.475043       -0.386848     -0.000192069    -0.000900993
                    -0.000709726     0.000470537        -0.427142       -0.874088     -0.000121584    -0.000901472        0.0310809         0.22816
281800                   0.61074      -0.0127488     -0.000474221    -0.000935271         0.276876         0.74097      -0.00064656      0.00043766
                    -0.000518267     -0.00104514        -0.163644       -0.165572      0.000195142     0.000164974        -0.434946       -0.869614
                        0.276744        0.741242      0.000192026     0.000122215         0.470105       -0.390432     -0.000201834     -0.00089522
                    -0.000704206     0.000477508        -0.434701       -0.869666     -0.000130894     -0.00089615        0.0343863          0.2303
[End]