! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:22 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=190; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0470053       -0.264312     -0.000144421     7.20063e-05         0.871235        0.410906      0.000337655    -0.000206355
                    -0.000145841     0.000103139        -0.294451        -0.27481      -0.00026849     1.88798e-05         0.653655       -0.640723
                        0.871331         0.41082     -0.000228435     2.46587e-05         0.233789         -0.1319      0.000335116     8.14857e-05
                     0.000269028    -7.15672e-05         0.653407       -0.640632      0.000230781     0.000147532        -0.269005       -0.299538
281800                -0.0490837       -0.263102     -0.000144532     7.30694e-05         0.874125         0.40526      0.000333456     -0.00020903
                    -0.000144517     0.000104127        -0.294145       -0.274894     -0.000268912     2.11779e-05         0.647647       -0.646902
                        0.874223        0.405173     -0.000228339     2.62796e-05         0.232453       -0.132598      0.000335842     7.73772e-05
                     0.000269111    -7.41073e-05           0.6474       -0.646806      0.000232958     0.000146703        -0.274682       -0.294113
[End]