! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:37 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=150; L_y=160; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.178307       -0.295703      0.000538672     0.000122449          0.90583        0.244995      0.000277478     0.000199074
                     0.000565386    -3.96776e-05        -0.130357       -0.305134      3.76009e-05     0.000265668          0.88655        0.322832
                        0.905994        0.245051     -7.95799e-05      0.00022584         0.302927       -0.165518     -0.000283253     1.84602e-05
                     0.000158586      0.00032649         0.886342        0.322726     -0.000411494    -6.17401e-06         0.295958       -0.149865
281800                 -0.179972       -0.294181      0.000536322     0.000118961         0.907723        0.238523      0.000273607     0.000199313
                      0.00056408    -3.85061e-05        -0.132272       -0.303865      3.48132e-05     0.000264857         0.888948        0.316581
                        0.907884        0.238576     -7.79882e-05     0.000226295         0.301219        -0.16771     -0.000285821     1.70056e-05
                     0.000160582     0.000324639         0.888743        0.316477     -0.000409262    -3.66974e-06         0.294483       -0.151856
[End]