! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:55:51 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=80; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.014814       0.0149681     -0.000247244    -0.000198969       -0.0696525        0.997367      0.000119314     0.000132898
                    -0.000267524    -0.000154414        0.0538096        0.172652      0.000110671     1.25502e-05        -0.246074        0.952197
                      -0.0696197        0.997364      0.000124459     1.88628e-05       -0.0125557        -0.01689     -0.000398142     7.17187e-05
                     0.000171919     5.47833e-05        -0.245934        0.952245     -0.000357465     7.05614e-05         0.130705       -0.125018
281800                -0.0145673       0.0130632     -0.000249228    -0.000197775       -0.0628373         0.99785      0.000150921     3.72226e-05
                    -0.000269171    -0.000152838         0.055092        0.170914      0.000109918     1.14262e-05        -0.239891        0.953948
                      -0.0628035        0.997847       0.00012411     1.80988e-05       -0.0127791      -0.0147965     -0.000368391     2.49136e-05
                     0.000172434     5.33483e-05         -0.23981        0.954045     -0.000358238     7.35574e-05         0.129399       -0.124545
[End]