! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:58 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=180; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.260926      -0.0787869     -0.000107613    -0.000163242         0.937456       -0.216601     -1.11383e-06     4.51999e-05
                    -0.000134954    -0.000159501         -0.86491       0.0124154     -8.58209e-05     0.000185053        -0.360014         -0.3489
                        0.937454       -0.216668      -0.00011035     0.000129677         0.199892        -0.18529     -0.000119522     8.69496e-05
                     2.64048e-05     5.29429e-05        -0.360031       -0.348905     -4.46452e-06     7.05909e-05         0.015572         0.86478
281800                 -0.260368      -0.0764484     -0.000108484    -0.000163179         0.936294       -0.223042     -1.14958e-06     4.48301e-05
                    -0.000135754    -0.000158825        -0.866293       0.0169147     -8.31434e-05      0.00018508        -0.361589       -0.343617
                         0.93629       -0.223111     -0.000110121      0.00013192         0.197913        -0.18565     -0.000118166     8.83934e-05
                     2.81819e-05     5.21362e-05        -0.361609       -0.343624     -5.49192e-06     6.84449e-05        0.0281029        0.865922
[End]