! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:31 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=140; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.76966        0.594532     -0.000570261     -0.00165694         0.227346       0.0472286      0.000910654     0.000635645
                     -0.00056568     -0.00168726        -0.977419        0.118259      0.000275644     0.000113657         0.120595        0.125436
                         0.22745       0.0471936      2.97078e-05     0.000284572         0.469209        0.851863      0.000409715    -0.000330823
                      0.00092496     0.000665939         0.120426        0.125447       0.00125197    -0.000400937        -0.157738        0.971776
281800                 -0.767251        0.597609     -0.000579219     -0.00165806         0.227765       0.0455558      0.000913666     0.000628325
                    -0.000574826     -0.00168914         -0.97675        0.122436      0.000271862     0.000103909         0.122371        0.124919
                        0.227869       0.0455156      3.28341e-05     0.000282466         0.478423        0.846701      0.000401276    -0.000335471
                     0.000929115     0.000654041         0.122201        0.124928       0.00123312    -0.000433393        -0.143666        0.973802
[End]