! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:13:00 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=200; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.153075      -0.0367626     -2.22213e-05    -1.98654e-05         0.343828       -0.925583      2.77315e-05     -0.00010418
                    -3.34289e-05    -4.15777e-06        -0.241349       -0.121742      -7.9966e-05     4.93747e-05         0.330249       -0.904097
                        0.343856       -0.925613     -0.000109548     8.31322e-05        -0.139793      -0.0719801     -9.96527e-06    -2.38198e-05
                    -2.96996e-05    -8.26164e-05         0.330219       -0.904312     -9.50148e-06    -1.26035e-06        -0.262817       -0.062614
281800                 -0.151986      -0.0384229      5.17834e-05    -2.46437e-05         0.335393       -0.928793       2.0102e-05    -0.000103967
                    -3.80134e-05    -1.28415e-06        -0.239703       -0.122098     -7.64162e-05     5.04113e-05         0.320528       -0.907981
                        0.335394       -0.928834     -9.17119e-05     8.78236e-05        -0.141308      -0.0674405     -1.37055e-05    -2.62554e-05
                    -2.64684e-05    -8.19571e-05         0.320377       -0.908164     -9.04477e-06    -4.22526e-06        -0.263081      -0.0555549
[End]