! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:57:19 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=90; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.786153        0.608424      0.000542137     6.98209e-05        -0.105508      -0.0116839      0.000166116    -0.000532493
                     0.000547585     1.35062e-05        -0.222592      -0.0572927     -0.000378602    -0.000108228         0.815645       -0.530949
                       -0.105502      -0.0117093     -0.000168678    -0.000276327         0.635506        0.764462      0.000184512     0.000110555
                     0.000188997    -0.000471021         0.815811       -0.531043      0.000363869    -2.12706e-05        0.0376796       -0.226663
281800                 -0.783168        0.612451      0.000544132     6.75101e-05        -0.104497      -0.0107161      0.000162256    -0.000534935
                     0.000551153     1.27321e-05        -0.221002      -0.0560156     -0.000378123    -0.000105883         0.812009       -0.537287
                        -0.10449      -0.0107393     -0.000168434    -0.000271902         0.644075        0.757412      0.000185239     0.000107385
                     0.000186622    -0.000474415         0.812175       -0.537378       0.00036205    -2.56768e-05        0.0348321       -0.225239
[End]