! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:01:48 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=120; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.338673       -0.126748      1.00841e-05    -0.000779212         0.932199      0.00544606      0.000126321    -0.000862854
                    -5.14325e-05    -0.000781621       0.00151439       -0.266693      5.19098e-05     -0.00111832         0.781438        0.564115
                        0.932182      0.00534697      4.97218e-05     -0.00102781         0.340038       -0.122824      0.000312848     -0.00114602
                     0.000128226    -0.000837242         0.781289        0.564349      0.000325521     -0.00116202         0.252623       -0.085411
281800                 -0.338999       -0.124504      8.39726e-06    -0.000778466         0.932397     -0.00130662      0.000121187    -0.000865529
                    -5.66375e-05    -0.000781461     -0.000805388       -0.266366      4.33333e-05     -0.00111907         0.785335        0.558835
                        0.932378     -0.00140369      4.19868e-05     -0.00102792         0.338558       -0.125493       0.00030146     -0.00115117
                      0.00012382    -0.000841075         0.785175         0.55907      0.000314264     -0.00116682         0.251888      -0.0865435
[End]