! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:11:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=200; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.155228        -0.12403     -9.44585e-05     0.000239436         0.480669        0.854754     -0.000346718     0.000179113
                    -7.26498e-05     0.000310504         -0.30892       -0.132092     -3.34699e-05     0.000311202         0.853415        0.398401
                        0.480206        0.854287      3.70469e-05     0.000298945         0.186568      -0.0681938     -0.000307063     0.000283741
                    -0.000360158     0.000220007         0.853504         0.39837      -0.00026413     0.000340668          0.29963        0.151965
281800                  0.153365       -0.125424     -9.25179e-05     0.000239454         0.486334        0.851686     -0.000344297     0.000180787
                    -7.14028e-05     0.000311435        -0.310637       -0.130215      -3.1241e-05     0.000312392         0.855791        0.392544
                        0.485859         0.85122       3.8929e-05     0.000298764          0.18591      -0.0683247     -0.000304864     0.000285978
                     -0.00035743     0.000223111          0.85588        0.392511     -0.000263484     0.000343862         0.301339        0.150459
[End]