! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:53:26 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=200; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.180242      -0.0987543      4.58012e-05    -4.94769e-05         0.171189       -0.963057      0.000248799    -4.14651e-05
                     5.44227e-05    -3.96616e-05        -0.179345      -0.0972012      0.000206706     7.31292e-05          0.17329       -0.963099
                        0.171192       -0.963256      0.000198005     9.76137e-05        -0.202854       0.0309866      8.67912e-06    -4.99108e-05
                      0.00022936    -4.03224e-05         0.173369       -0.963182      5.95597e-06    -6.61637e-05         -0.20151       0.0289068
281800                 -0.180049       -0.100886      5.21896e-05    -0.000117312         0.162332       -0.964757       0.00015423    -7.36788e-06
                     5.47484e-05    -0.000124055         -0.17912      -0.0992459      0.000182069     0.000128563         0.164297       -0.964666
                        0.162493       -0.964745      0.000200662      8.5891e-05        -0.202998       0.0364782     -9.23751e-06    -1.53134e-05
                     0.000217596    -7.83562e-05          0.16439       -0.964835      2.32607e-05     6.21177e-06        -0.201678       0.0344566
[End]