! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:59:07 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=110; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0121698       -0.268996     -9.63314e-05    -8.14449e-05         0.812868        0.517089      -5.0114e-05    -5.14737e-05
                     -7.6279e-05    -9.78895e-05        -0.078917       -0.259147      4.10869e-05    -1.37884e-06         0.887444        0.373307
                        0.812752        0.516776      4.20203e-05    -6.87002e-06         0.238422       -0.125096      0.000160968     1.37458e-05
                    -6.70055e-05     -5.9816e-05         0.887303        0.373304      0.000116226     0.000132974         0.240483       -0.124755
281800                0.00983748       -0.268313     -9.80899e-05    -7.86796e-05         0.816401        0.511893     -4.92998e-05    -4.99897e-05
                    -7.70701e-05    -9.66355e-05       -0.0808935       -0.257744      4.26404e-05     -1.7137e-06          0.89009        0.367511
                        0.816288        0.511581      4.20573e-05    -6.67255e-06         0.237174       -0.125798      0.000161055     1.34692e-05
                    -6.72217e-05    -5.90486e-05         0.889949        0.367508      0.000115508     0.000133385         0.239222       -0.125537
[End]