! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:54 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=170; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0638359       0.0560477      0.000229107     0.000332406         0.346036       -0.934183     -1.22413e-05    -0.000227692
                      0.00024372     0.000303651        -0.220823       0.0183499     -0.000211464     9.50072e-05         0.689662       -0.688975
                        0.346081       -0.934199     -0.000245683     9.22864e-05        -0.011728      -0.0839816      0.000350397     7.79145e-05
                     7.34124e-05    -0.000232697          0.68973       -0.688715      0.000327122     9.99714e-05        0.0188523       -0.220983
281800                -0.0623525       0.0537098       0.00023263     0.000326812         0.337498       -0.937542     -7.13803e-06    -0.000222036
                     0.000245039     0.000297833        -0.217342       0.0207541     -0.000202405     0.000100699          0.68253         -0.6971
                        0.337549       -0.937551     -0.000237733     9.96629e-05       -0.0136205      -0.0810033      0.000346011     7.95332e-05
                     7.69331e-05    -0.000226406         0.682597       -0.696836      0.000322351     0.000101532        0.0164269         -0.2179
[End]