! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:44 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=150; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.862404        0.433492     -0.000145371     5.92912e-05         0.239454        0.103875     -0.000729457    -0.000462686
                    -7.59271e-05     2.86347e-05        -0.947249        0.225825     -0.000169787    -0.000190184         0.177959        0.140833
                        0.239307        0.103871     -0.000233911    -0.000112214         0.271315        0.926267      0.000216056     0.000142936
                    -0.000658536    -0.000533619         0.177993        0.140742       0.00034994     2.23789e-05      -0.00243703        0.973679
281800                 -0.860624         0.43693     -0.000143577     5.93575e-05         0.240407        0.102024     -0.000733237     -0.00045709
                    -7.51557e-05     2.88857e-05        -0.946181        0.229716     -0.000172341    -0.000192506         0.179627        0.139595
                        0.240258        0.102019     -0.000232462    -0.000113203           0.2823        0.922939      0.000215826     0.000138668
                    -0.000660546    -0.000528527         0.179663        0.139505      0.000345446     5.65142e-06        0.0107094        0.973496
[End]