! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:40 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=140; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.396974       -0.631578     -0.000626465     0.000734018         0.387573       -0.541237       0.00091969     0.000561911
                    -0.000676851     0.000844352        0.0545353       -0.360269      0.000710719     0.000958966         0.852777        0.372998
                        0.387631       -0.541276       0.00070514     0.000922233        -0.725663       -0.171912       0.00205239     -0.00018196
                     0.000839535     0.000514952         0.853223        0.372551        0.0018749    -0.000168546         0.227404       -0.284819
281800                  -0.40037       -0.631378     -0.000624033     0.000742202          0.37943       -0.544727      0.000929209     0.000552956
                    -0.000671162     0.000853847        0.0511862        -0.35947      0.000729064     0.000953481         0.856519        0.365615
                        0.379486       -0.544753      0.000721299     0.000920983        -0.730885       -0.156202        0.0020562    -0.000215115
                     0.000851245     0.000508272         0.856936        0.365181       0.00188218    -0.000199855         0.224068       -0.285829
[End]