! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:54:21 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=70; L_y=160; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0137463       0.0659017     -4.09728e-05    -0.000229873        -0.136554        0.988376      0.000156783     0.000129147
                    -3.05693e-05    -0.000249613        0.0571576        0.201061      6.32647e-06    -4.86703e-05        -0.278812        0.937324
                       -0.136474        0.988256      4.73598e-05      4.0643e-05        0.0310825      -0.0596692     -0.000279847     0.000207823
                       4.802e-05     0.000106311        -0.278712        0.937296      -0.00016891     0.000179332         0.157724       -0.137183
281800                 0.0143757       0.0640045     -4.17276e-05    -0.000230139         -0.12992        0.989386       0.00015626     0.000127606
                    -3.24414e-05    -0.000248902         0.058609        0.199405      6.52178e-06    -4.89497e-05        -0.272867        0.939292
                       -0.129841        0.989263      4.70649e-05     4.02826e-05        0.0303944       -0.058086     -0.000254794     0.000210065
                     4.82509e-05     0.000105465        -0.272756        0.939309     -0.000168281     0.000181019         0.156301        -0.13701
[End]