! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:57:08 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=90; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.378723        0.695693     -0.000273416    -0.000168891        -0.563305        0.233442     -0.000155098     0.000262114
                    -0.000230733     -0.00016555       -0.0155301       0.0823353     -0.000328895      0.00046943         0.273522       -0.958302
                       -0.563306         0.23332     -0.000232964     0.000572466         0.759895        0.223966      0.000493087     0.000195941
                    -6.88813e-05     0.000271036         0.273658       -0.958049      0.000555849     0.000107808        0.0303237      -0.0781563
281800                 -0.373543        0.698936     -0.000276839    -0.000165926        -0.560709        0.238301     -0.000152775      0.00026488
                    -0.000233738    -0.000164254       -0.0141038        0.080513     -0.000322906     0.000475464         0.266123       -0.960561
                        -0.56071        0.238175     -0.000227687     0.000576012          0.76254        0.216246      0.000498312     0.000194279
                    -6.62816e-05     0.000272953         0.266262       -0.960308      0.000559167     0.000105585        0.0293913      -0.0763196
[End]