! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=140; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.711987       -0.261899      7.18759e-05      8.4431e-05        -0.224125        -0.61128     -8.56227e-05     0.000123301
                     8.08003e-05     8.48179e-05        -0.899997        0.404465     -0.000206597    -9.07047e-05        -0.151574      -0.0544684
                       -0.224104       -0.611189     -0.000158914    -0.000103293        -0.373273         0.66038      0.000365678     3.60394e-05
                    -4.20522e-05     0.000106257        -0.151557      -0.0544417      0.000222803     9.72922e-05         0.438666        0.883819
281800                 -0.715158       -0.259395      7.24092e-05     8.49264e-05        -0.229921       -0.606474      -8.4174e-05     0.000125721
                     8.10447e-05     8.49678e-05        -0.898084        0.409306     -0.000206296    -8.76942e-05        -0.150578      -0.0526055
                       -0.229899       -0.606382     -0.000159304    -0.000102424        -0.362768        0.668623      0.000367231     3.13175e-05
                    -3.96846e-05     0.000105795        -0.150561      -0.0525787      0.000227616     9.47945e-05         0.449798        0.878491
[End]