! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:07:20 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=160; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.65418        0.720363      0.000372817     0.000567059         0.229845      0.00867944     -4.73226e-05     7.29354e-05
                     0.000388513     0.000445011        -0.800009        0.544805     -0.000445396    -0.000137194         0.241478       0.0676428
                        0.229838       0.0086837     -0.000214328    -0.000207828         0.598187        0.767542     -0.000158675     0.000225619
                    -0.000255886     8.52247e-05         0.241496       0.0676642     -0.000345143     0.000116549         0.399892        0.881408
281800                 -0.651195        0.723094      0.000377342     0.000567144         0.229796      0.00702125     -4.63139e-05     7.14929e-05
                     0.000394951     0.000446182         -0.79776        0.548203      -0.00044416    -0.000132416         0.241762       0.0656972
                        0.229787      0.00703147     -0.000217499    -0.000205604         0.606033        0.761394      -0.00016102     0.000227499
                    -0.000251515     8.83762e-05         0.241784       0.0657212     -0.000345062     0.000120349          0.40991        0.876864
[End]