! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:38 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=140; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.210988      -0.0871586      3.46862e-05     0.000113864         0.749785       -0.621046     -0.000141316    -7.99549e-05
                      2.8955e-05     7.90982e-05        -0.817861       -0.171598     -5.22407e-05       2.032e-05        -0.276759       -0.473882
                        0.749628       -0.620912     -8.38576e-05    -0.000102793       -0.0463403       -0.223475      8.78829e-05     1.74087e-05
                    -7.28036e-05    -0.000104701        -0.276768       -0.473969      0.000232488     1.55655e-05        -0.251488        0.796794
281800                 -0.209366      -0.0864421      3.42285e-05     0.000112955          0.74518       -0.627206     -0.000141939     -7.8381e-05
                      2.9026e-05     7.86969e-05        -0.820501       -0.167787     -5.04808e-05     2.04037e-05        -0.280425       -0.468495
                        0.745024       -0.627075     -8.41347e-05    -0.000101853       -0.0494311       -0.220996      8.81052e-05     1.64013e-05
                    -7.61185e-05    -0.000105768        -0.280432       -0.468581      0.000233494     8.78427e-06        -0.238869        0.802561
[End]