! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:07:31 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=170; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.196826      -0.0759543      9.36736e-05    -4.49121e-05         0.389562        0.896689         7.49e-05     0.000238652
                      1.4366e-05    -1.14282e-05        -0.094744       -0.194939     -0.000155888    -0.000128933         0.704475         0.67594
                        0.389359        0.896517     -0.000149345    -0.000123901         0.189817      -0.0920095      3.09662e-05    -2.24814e-05
                     7.17326e-05      0.00019469         0.704326        0.675916      7.44746e-07    -4.42101e-05         0.198675        0.086668
281800                   0.19532      -0.0777206      9.36766e-05    -4.39052e-05         0.395457        0.894283       7.7725e-05     0.000237319
                     1.56494e-05    -9.93938e-06       -0.0971347       -0.194683     -0.000157301    -0.000128968         0.708856        0.671076
                        0.395251        0.894113     -0.000151394    -0.000123946         0.188896      -0.0921702      3.10465e-05    -2.60408e-05
                     7.21889e-05     0.000193432         0.708708        0.671056      3.76507e-08    -4.66968e-05         0.199694       0.0863979
[End]