! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:09:42 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=180; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.220045        -0.13268      0.000223754    -0.000378725         0.872258       -0.415544      0.000105059     -0.00065541
                     0.000200045    -0.000424034        -0.368135        0.350038     -0.000294828    -0.000472858         0.805726       -0.303346
                        0.872319       -0.415438     -0.000287273    -0.000490968        0.0356176       -0.254276     -0.000686017    -0.000526904
                     7.77835e-05    -0.000679734         0.805845       -0.303369      -0.00069491    -0.000522314         0.507366       0.0209067
281800                  -0.21864        -0.13187      0.000218379    -0.000380116         0.868316       -0.424706      9.76082e-05    -0.000653457
                      0.00019177     -0.00042681        -0.363733        0.351205     -0.000299039    -0.000466929         0.803952       -0.311903
                        0.868373         -0.4246     -0.000291462    -0.000483678        0.0301386       -0.253345     -0.000690856    -0.000514225
                     6.74648e-05    -0.000676744         0.804066       -0.311924     -0.000696322    -0.000512351         0.505218       0.0145726
[End]