! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:05 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=130; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.164207       0.0660246     -6.21428e-05    -8.98237e-06       -0.0814667       -0.980871      0.000175138    -0.000154623
                    -8.55979e-05    -1.65368e-05        -0.282989       -0.131189      0.000206558    -0.000236484        -0.914995       -0.255465
                      -0.0814647       -0.980614      0.000174401    -0.000183806         0.151086      -0.0921588        4.749e-06     0.000216263
                     0.000349177    -1.44127e-05        -0.914822       -0.255639     -7.28198e-05     8.37373e-05         0.310093       0.0342482
281800                  0.164239       0.0634478     -5.83762e-05    -1.26615e-05       -0.0886503       -0.980412      0.000171809    -0.000155507
                    -8.63929e-05    -2.41439e-05        -0.284914       -0.128262      0.000203797    -0.000239472        -0.917002       -0.247473
                      -0.0886501        -0.98016      0.000173452    -0.000187541         0.150214        -0.09183      9.93164e-06     0.000217903
                     0.000345989    -1.60913e-05        -0.916819       -0.247641     -6.87448e-05     8.78813e-05         0.310833        0.032358
[End]