! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:11:49 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=200; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0504842        0.157056     -2.84518e-05     0.000294355        -0.227583        0.959694      -0.00039906    -9.73513e-05
                     4.83954e-05     0.000436892       -0.0935589      -0.0722643     -0.000375624     7.77085e-05        0.0565178        0.991302
                       -0.227513          0.9597     -0.000282749     3.81812e-05         0.115616       -0.117671       8.9935e-05    -0.000422492
                    -0.000425392    -0.000140875        0.0566245        0.991231       -3.673e-06    -0.000321274       -0.0847083       0.0824516
281800                 0.0516721        0.155279     -2.29651e-05     0.000293313        -0.221372        0.961374     -0.000400138    -9.46648e-05
                     5.26485e-05     0.000437365       -0.0940436      -0.0739789     -0.000377199      7.9843e-05         0.063466        0.990709
                       -0.221301        0.961377     -0.000284634     4.06352e-05         0.114363        -0.11705      8.75815e-05    -0.000423498
                    -0.000428994    -0.000138704        0.0635735        0.990633     -4.71625e-06    -0.000323806       -0.0838052       0.0853969
[End]