! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:48 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=170; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0904235        0.126622     -0.000459065        0.000352         0.507719       -0.847245     -0.000263555      1.7753e-05
                    -0.000464476     0.000348955        -0.138806        0.182007     -0.000157408    -5.49752e-05         0.647156       -0.726896
                        0.507776       -0.847068      -0.00017115    -4.69777e-05         0.069164       -0.139259      0.000150395    -0.000596649
                    -0.000239748     2.51078e-05         0.647212       -0.726768      0.000171909    -0.000614172         0.164894       -0.158757
281800                -0.0880482        0.124995     -0.000455484     0.000354931         0.500307       -0.852131     -0.000261868      1.9067e-05
                    -0.000461581     0.000351494        -0.135649        0.181609     -0.000156576    -5.43234e-05         0.640953       -0.733059
                        0.500365       -0.851956     -0.000170462    -4.60198e-05        0.0663884       -0.137611      0.000145555    -0.000596388
                    -0.000237409     2.54865e-05            0.641       -0.732941      0.000167051     -0.00061543         0.162043       -0.158514
[End]