! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:41 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=160; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0646264       -0.114056     -0.000127691     0.000164787         0.404419        0.904861     -0.000292268     0.000730492
                     4.54592e-05     0.000123658        -0.226472       -0.154055     -0.000428954     0.000658921         0.918036       -0.285808
                        0.404022        0.904974     -0.000342422     0.000601676         0.128254       0.0278911      -7.0914e-06     0.000371523
                    -0.000145353     0.000621656         0.917936       -0.286101      5.04619e-05     0.000490488        0.0988043       -0.255339
281800                  0.062196       -0.116903     -0.000134243     0.000168817          0.41413        0.900265      -0.00028448     0.000736703
                     4.28056e-05      0.00012654        -0.225713       -0.152247     -0.000422585     0.000662665         0.915638       -0.294929
                        0.413736        0.900382     -0.000339498     0.000606585         0.129409       0.0288059     -1.05896e-06     0.000378079
                    -0.000135978     0.000624137         0.915536       -0.295206      5.71661e-05     0.000493678        0.0942322        -0.25531
[End]