! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:47 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=150; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.150629        0.122129      0.000292348     0.000174071        0.0369328        -0.97997     -3.37448e-06    -5.07243e-05
                     0.000257649     7.48854e-05        -0.339481        0.184341     -3.29441e-05    -6.73143e-05        -0.879589        0.276734
                       0.0369694       -0.980309      1.37611e-05    -0.000120076         0.159402       -0.110421     -0.000116422    -9.70895e-05
                     9.46299e-05    -4.97254e-05        -0.879526        0.276702     -0.000161705    -0.000125619         0.383987      -0.0432356
281800                  0.151273        0.119661      0.000295281     0.000173346        0.0299019       -0.980414     -4.04863e-06    -5.27173e-05
                     0.000262299     7.35548e-05        -0.337271        0.187879      -3.2272e-05    -6.56628e-05        -0.877087        0.284876
                       0.0299374       -0.980754      1.26014e-05    -0.000120218         0.158292       -0.110195     -0.000119423    -9.80573e-05
                       9.387e-05    -5.15018e-05        -0.877024        0.284841     -0.000165956    -0.000127591         0.383414      -0.0461566
[End]