! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:11 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=170; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.215043        -0.17953      0.000421785     0.000799498         0.942118        0.184007      0.000840673     0.000427126
                     4.09877e-05     0.000942057        -0.619603        -0.50144       0.00125595     0.000536931        0.0278328       -0.601582
                        0.941966        0.183806       0.00101086     0.000610203         0.266798      -0.0855753       0.00125177    -0.000339155
                     0.000959928     0.000987053        0.0277221       -0.601543       0.00144247    -0.000718122        -0.660524        0.444935
281800                 -0.216677       -0.176939      0.000438658     0.000802792         0.943871        0.175411      0.000857559     0.000409738
                     5.91688e-05     0.000960786        -0.633565       -0.499068       0.00128728     0.000502256        0.0122648       -0.589378
                        0.943713        0.175206       0.00103284     0.000589903         0.265788      -0.0874313       0.00125113    -0.000381571
                      0.00100405     0.000979436        0.0121516       -0.589337       0.00142582    -0.000784032        -0.650842        0.475159
[End]