! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:11:07 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=190; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0893569      -0.0777149      -0.00102578    -7.67611e-05        0.0882053        0.988949      0.000758745    -0.000327854
                    -0.000894083    -6.98052e-05        -0.221125       -0.152758      0.000793482    -0.000131075          0.23411        0.934413
                       0.0883038        0.989022      0.000786553    -0.000123011       -0.0741511       0.0923183       -0.0005067     0.000600843
                     0.000657603    -0.000534745          0.23415        0.934278     -0.000676307     0.000563278        -0.122959         0.23899
281800                -0.0899355      -0.0794135      -0.00102719    -6.87364e-05        0.0950993        0.988123      0.000757125    -0.000333282
                    -0.000894216    -6.44568e-05        -0.222456       -0.153847      0.000792298    -0.000138368         0.240661         0.93225
                       0.0951979        0.988194      0.000785599     -0.00013081       -0.0730969       0.0951243     -0.000498921     0.000604382
                      0.00065335    -0.000541017           0.2407        0.932116     -0.000669982     0.000568405        -0.120168        0.242319
[End]