! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:02 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=180; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.36373       -0.369349     -4.29538e-05      3.7615e-05         0.788424       -0.330521     -0.000382101    -0.000784866
                     -0.00023023    -7.29928e-06        -0.362065        -0.37052     -0.000308325    -0.000803663         0.789068       -0.329711
                        0.788591       -0.330272     -0.000282626    -0.000865709      -0.00849482       -0.518083      -0.00104024     3.34491e-05
                    -0.000378647    -0.000822093         0.789085       -0.329803       -0.0010301     9.58273e-06      -0.00946859       -0.517769
281800                 -0.364443       -0.368189     -4.18578e-05     3.53204e-05         0.785588       -0.337709     -0.000390917    -0.000784343
                    -0.000233793    -3.92757e-06        -0.362778       -0.369365     -0.000317543     -0.00080389         0.786238       -0.336903
                         0.78577       -0.337457      -0.00029133    -0.000867148       -0.0165208        -0.51756      -0.00104556      4.9726e-05
                    -0.000388297      -0.0008223         0.786253       -0.336994      -0.00103397     2.63849e-05       -0.0174944       -0.517232
[End]