! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:58:03 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=100; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0416541        0.112309     -0.000534414    -0.000169703         0.376914       -0.918449     -5.71018e-05    -3.51292e-05
                    -0.000570988    -0.000134422       -0.0425116        0.112208     -0.000122016     3.60956e-06         0.376823       -0.918486
                        0.376967       -0.918415     -0.000115809     6.66053e-05        0.0493012       -0.109173     -0.000614657    -0.000333263
                    -8.14569e-05    -7.74788e-05         0.376835       -0.918471     -0.000522748    -0.000330224        0.0485763        -0.10971
281800                -0.0398085        0.110899     -0.000534928    -0.000169463         0.369998       -0.921509     -5.69258e-05    -3.51194e-05
                    -0.000573275    -0.000132259       -0.0406674        0.110805     -0.000122441     3.93903e-06         0.369907       -0.921544
                        0.370051       -0.921476     -0.000114754     6.69703e-05        0.0479909       -0.107615     -0.000620287    -0.000326449
                    -8.28623e-05    -7.78629e-05         0.369917       -0.921532     -0.000527353    -0.000325079        0.0472633       -0.108147
[End]