! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:29 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=120; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                   0.05719        0.221011      0.000152977     0.000220041        -0.299555        0.926362      2.01827e-05    -4.64778e-05
                     0.000168491     0.000233121        0.0477708        0.163165      4.95895e-05    -3.53822e-05        -0.243464         0.95482
                         -0.2995        0.926367      2.35255e-05    -9.35365e-05         0.175751       -0.145672      0.000235543    -0.000120753
                     3.56325e-05    -7.17641e-05        -0.243516        0.954925      0.000231819     -0.00011797         0.120117       -0.120325
281800                 0.0587515        0.219426      0.000154727     0.000219111        -0.293716        0.928508      1.95523e-05    -4.57914e-05
                     0.000170684     0.000232136         0.049022        0.161425      4.88271e-05    -3.54764e-05        -0.237297        0.956604
                       -0.293661        0.928512      2.25907e-05    -9.34982e-05         0.174244       -0.145709      0.000235653    -0.000122328
                     3.48409e-05    -7.17222e-05        -0.237346        0.956709      0.000231562    -0.000119446         0.118832       -0.119755
[End]