! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:48 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=160; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0344988      -0.0163074      0.000866418     0.000653865       -0.0156388        0.999071     -0.000877365     0.000199924
                      0.00083183     0.000713803       -0.0768044      -0.0621573     -0.000927575     0.000148573        0.0494538        0.993617
                      -0.0157519        0.999236     -0.000978496     0.000120283       -0.0349456       0.0152174       0.00066169    -0.000792849
                     -0.00107612    -6.88213e-05        0.0495266        0.993958      0.000713816    -0.000786056       -0.0702005       0.0694922
281800                -0.0345363      -0.0181703      0.000873154      0.00065036      -0.00876877        0.999123     -0.000875052     0.000207505
                     0.000837653     0.000710398       -0.0772206      -0.0639109     -0.000927466      0.00016117        0.0563754        0.993107
                      -0.0088795        0.999285     -0.000976365      0.00012811       -0.0348037       0.0175583       0.00065099    -0.000797404
                     -0.00107776    -6.23493e-05        0.0564477        0.993445      0.000705933    -0.000792618       -0.0694387       0.0722536
[End]