! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:59:21 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=110; L_y=90; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0825378         0.15369      0.000326991      0.00034605         0.507963       -0.843624      0.000320136     7.08815e-05
                     0.000298775     0.000377216       -0.0251856       0.0472443       0.00035523     0.000199297         0.224973        -0.97279
                        0.507814       -0.843539      0.000416994     0.000225569        0.0971986        -0.14488      0.000652198    -6.03778e-05
                     0.000347439     0.000102216         0.224865       -0.972916      0.000598364    -2.74919e-05      -0.00184435      -0.0535418
281800                 -0.080275        0.153001      0.000331958      0.00034697         0.501923       -0.847575      0.000323891       7.084e-05
                     0.000303501     0.000377968       -0.0240936       0.0452657      0.000358381     0.000195984         0.217266       -0.974665
                        0.501773       -0.847488      0.000419866     0.000224394        0.0955497       -0.143972      0.000649394     -6.6317e-05
                     0.000349669     0.000100926         0.217154       -0.974787      0.000599989    -3.41273e-05      -0.00254754        -0.05125
[End]