! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:45 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=160; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                   -0.7692        0.628231      -0.00194465     -0.00109435        -0.114083     -0.00968056      0.000118559    -5.15865e-05
                     -0.00203014     -0.00111112        -0.114375        0.991089     -7.81803e-05    -0.000149881       -0.0534326       0.0362269
                       -0.114223     -0.00975358      0.000359581    -5.65632e-05         0.653272        0.748092     -0.000287932       0.0012822
                    -4.82228e-05    -0.000195534       -0.0535517       0.0357066     -0.000811947      0.00131549         0.961615        0.266144
281800                 -0.765917        0.632377      -0.00196153     -0.00108868        -0.113341     -0.00866687      0.000122073    -5.66241e-05
                     -0.00204235     -0.00110395        -0.108783        0.991688     -7.62896e-05    -0.000146508       -0.0535489       0.0368909
                       -0.113477     -0.00873968      0.000373374    -5.77657e-05         0.661777        0.740707     -0.000274359        0.001268
                    -4.26616e-05    -0.000196069       -0.0536587       0.0363753     -0.000797032      0.00132544         0.964086        0.256937
[End]