! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:14 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=180; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.324606       -0.180121     -0.000596917       0.0001743         0.340791        0.863861       0.00039101    -0.000239638
                    -0.000523997     0.000254149        -0.238762       -0.162904      0.000419636    -0.000231642         0.271219        0.918069
                        0.340942        0.863776      0.000278303    -0.000283638        -0.114016        0.353274     -0.000249192     0.000271029
                     0.000358316    -0.000222739         0.271337        0.918013     -0.000191991     0.000267311        -0.111839        0.266544
281800                  -0.32631       -0.180573     -0.000597498     0.000178089         0.346707        0.860764       0.00038823    -0.000242954
                    -0.000522348     0.000256038         -0.24022       -0.163847      0.000416194    -0.000234907         0.277598        0.915611
                        0.346858        0.860679      0.000275034    -0.000286169        -0.109864        0.356376     -0.000246649     0.000273153
                     0.000356631    -0.000226298         0.277715        0.915555     -0.000190209     0.000269404        -0.108719        0.269704
[End]