! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:59:20 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=110; L_y=90; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.25426       -0.069663     -0.000360359    -0.000288212         0.922242       -0.283135      5.13645e-05     9.78425e-05
                    -0.000377033    -0.000276608        -0.232932      -0.0552604     -9.44021e-05     0.000185776         0.851501       -0.465978
                        0.921948       -0.282951     -4.59877e-05     0.000137998         0.171356       -0.200375       0.00013363    -0.000453286
                     6.14406e-05     0.000158342         0.851742        -0.46609      0.000145717    -0.000396868        0.0791273       -0.225918
281800                  -0.25343      -0.0674729     -0.000363943    -0.000284905         0.920616       -0.289637      5.28712e-05     9.94127e-05
                    -0.000381273    -0.000276226        -0.231487      -0.0537167     -9.40469e-05     0.000185886          0.84843       -0.472439
                         0.92031        -0.28945     -4.40856e-05     0.000137454         0.169133       -0.200463      0.000131315    -0.000454822
                     6.15182e-05     0.000160136         0.848669       -0.472548      0.000143129    -0.000399506         0.076346       -0.225016
[End]