! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:57:38 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=90; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.216524        0.974068     -0.000327226    -0.000155207       -0.0541421       0.0303572      0.000205183     0.000305819
                    -0.000370553    -0.000111703         -0.20605      -0.0753272     -0.000365991    -2.63863e-05         0.727477        -0.65005
                      -0.0544003       0.0300026     -0.000357897      5.0298e-05         0.944881        0.321009       0.00025761     4.40237e-05
                     0.000287903     0.000347932         0.727538       -0.649971      0.000377425    -2.18693e-06       -0.0517582       -0.213146
281800                  -0.21138        0.975209     -0.000328485     -0.00015409       -0.0537584       0.0306624      0.000208271      0.00030396
                    -0.000372955     -0.00011293        -0.204364      -0.0747235     -0.000365556    -2.44991e-05         0.722642       -0.656017
                      -0.0540229       0.0303003     -0.000357052     5.44356e-05         0.947866        0.312122      0.000259643       4.298e-05
                     0.000286878     0.000348126         0.722709       -0.655934      0.000378405    -4.84204e-06       -0.0546632       -0.210569
[End]