! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:32 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=170; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.267129       -0.346323        0.0004337    -0.000580434         0.895878      -0.0773198      0.000115774     0.000911909
                       0.0003821    -0.000640911        -0.267666        -0.34511     -0.000233371     0.000919634         0.896004      -0.0788122
                        0.895973      -0.0772859     -0.000209315      0.00108408         0.203628        -0.38691      0.000452613    -0.000153875
                     9.04441e-05      0.00100228         0.896059       -0.079132       0.00048446    -0.000163805         0.203163       -0.386472
281800                 -0.268069       -0.344795      0.000430296    -0.000579495         0.895534      -0.0845439      0.000124819     0.000914825
                     0.000374986    -0.000640114        -0.268589       -0.343582     -0.000226451     0.000925491         0.895648      -0.0860394
                        0.895645      -0.0845116     -0.000197785      0.00108927         0.198591       -0.388805      0.000453207    -0.000155692
                     9.92186e-05      0.00100256          0.89569      -0.0863603      0.000484528     -0.00016719         0.198123       -0.388364
[End]