! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:12:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=200; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.452153       -0.394327     -0.000469147     0.000453646         0.639386       -0.480683     -0.000442645    -0.000145125
                    -0.000481251     0.000450231        -0.468549       -0.311062     -0.000270584    -0.000351525         0.579391       -0.589629
                        0.639504       -0.480781     -0.000238158    -0.000316175        -0.253601         -0.5435      5.13254e-05    -0.000107853
                    -0.000490749    -0.000112727         0.579529       -0.589708     -1.02124e-05    -4.35512e-05        -0.319326       -0.462612
281800                 -0.453195       -0.393282      -0.00046752     0.000453459         0.634266       -0.487023     -0.000444706     -0.00014173
                    -0.000480288     0.000450684        -0.469199       -0.310457     -0.000219562    -0.000344713         0.573241       -0.595408
                         0.63458       -0.487128     -0.000242266     -0.00031542        -0.263149       -0.538987      4.82809e-05    -0.000105791
                    -0.000492409    -0.000107855         0.573378       -0.595482       2.6465e-05    -9.38332e-05        -0.328124       -0.456669
[End]