! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:58:22 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=100; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0142114       0.0616889     -7.77858e-05    -0.000243712        -0.126369        0.989869      4.06454e-05    -7.13984e-05
                    -0.000132819     2.20492e-06        0.0440852        0.134944      0.000200652     8.42011e-05        -0.206935           0.968
                       -0.126309        0.990162        0.0001045     2.87638e-05        0.0292846      -0.0561235     -0.000116553    -4.67339e-05
                     0.000166461    -6.44723e-05        -0.206938        0.967813       -3.613e-05    -6.28697e-05        0.0954317       -0.105108
281800                 0.0147965       0.0597775     -7.57633e-05    -0.000241583         -0.11972        0.990803      3.97604e-05      -7.222e-05
                    -0.000130521     4.20271e-06        0.0451439        0.133125      0.000201012     8.23122e-05        -0.200613        0.969535
                       -0.119657        0.991092      0.000107101     3.29225e-05        0.0286396      -0.0545168     -0.000115781    -4.68694e-05
                     0.000164892    -6.19275e-05        -0.200617        0.969346     -3.57753e-05    -6.32865e-05        0.0942924        -0.10426
[End]