! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=160; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.984581       -0.173656     -3.27128e-05    -0.000764337      -0.00125757     -0.00335962     -0.000271324    -0.000237658
                    -0.000103996      -0.0008338        -0.966929        0.170588     -0.000231126     -0.00015673         0.139884        0.126779
                     -0.00115695     -0.00343727      -0.00016588    -0.000147204         -0.56215        0.826596       -0.0009637    -0.000329225
                    -0.000327334    -0.000234687         0.139869        0.126287      -0.00103736    -0.000395495       -0.0760412        0.978837
281800                 -0.985403       -0.168959      -4.0202e-05    -0.000762463     -0.000440994     -0.00138084     -0.000272467     -0.00023325
                    -0.000110295    -0.000831838        -0.966036        0.174619     -0.000232925    -0.000152272         0.141671        0.126075
                    -0.000335865     -0.00145753     -0.000166875    -0.000143022        -0.548066         0.83601     -0.000959116    -0.000313893
                    -0.000328463    -0.000228779         0.141656        0.125613       -0.0010417    -0.000376776       -0.0623607         0.97964
[End]