! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:55:32 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=80; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.164325       -0.156473       0.00027127     0.000216025        -0.303516       -0.925293      0.000368762    -2.34036e-05
                      0.00023188     0.000302066         -0.11233        0.173079      0.000149779     0.000154637         0.580402       -0.787807
                       -0.303466       -0.925279      0.000200131     0.000152631        -0.039551         0.22344      0.000252981    -0.000145165
                     0.000269228     -0.00010782         0.580347       -0.787574      0.000263982    -0.000188499         0.132019       -0.158632
281800                 -0.166632       -0.157909      0.000275553     0.000214803         -0.31158       -0.921949      0.000369232    -2.73046e-05
                     0.000235998     0.000301263        -0.109916        0.172847      0.000151459     0.000153605          0.57494       -0.792196
                        -0.31153       -0.921936      0.000201887     0.000151757        -0.036511        0.226654      0.000251997    -0.000149033
                     0.000269467    -0.000109865         0.574882       -0.791959      0.000262004    -0.000191091         0.130264       -0.158137
[End]