! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:56:57 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=90; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.340843       0.0767476      0.000187646    -2.60339e-05        -0.919823          0.1773     -0.000110597    -0.000399619
                     0.000164831     -9.2326e-05         0.139265      -0.0816518      0.000354073    -9.17671e-05        -0.363337       -0.917607
                       -0.919709        0.177196      0.000366804    -0.000220101         0.345025      -0.0554467      0.000114843     5.54217e-05
                    -0.000142713     -0.00037751        -0.363074       -0.917913       4.0712e-05     2.38366e-05         0.157471      -0.0357127
281800                 -0.339675       0.0805425      0.000189353    -2.99938e-05        -0.918219        0.185969     -0.000115031    -0.000398463
                     0.000165154    -9.42504e-05         0.137697      -0.0838258      0.000353981    -9.48582e-05        -0.370343       -0.914846
                       -0.918104        0.185862      0.000363026    -0.000222977         0.344321      -0.0579772      0.000116538     5.37089e-05
                    -0.000146349    -0.000376372         -0.37008       -0.915154      3.89436e-05     2.35967e-05         0.157292      -0.0354572
[End]