! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:58:33 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=100; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0555801       -0.223657     -0.000246285     0.000766901         0.677712        0.697922     -0.000355403     -0.00010949
                    -0.000240349     0.000870681        -0.144043       -0.219742      9.96466e-05    -0.000248823        -0.874803       -0.407069
                        0.677322        0.697512      0.000165425    -0.000157988         0.225329      -0.0491326      0.000620903    -0.000457845
                    -0.000325848    -0.000174289        -0.874519       -0.406851      0.000629591    -0.000529545         0.260901      -0.0314684
281800                 0.0516954       -0.224743     -0.000242566     0.000767368         0.684847        0.690869     -0.000353588    -0.000102312
                    -0.000236783     0.000870186        -0.146694       -0.218071      9.78052e-05    -0.000252853         -0.87822       -0.399593
                         0.68447        0.690444      0.000163088    -0.000160064         0.225319       -0.049875      0.000610449    -0.000463813
                    -0.000328724    -0.000168638        -0.877936        -0.39937      0.000620138    -0.000536187         0.260809      -0.0328124
[End]