! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:01:10 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=120; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.147311       0.0153828      0.000674893     -0.00139977         0.130848        0.979805       0.00177361     0.000358193
                     0.000599524     -0.00141579       -0.0557889        0.207908       0.00173982     0.000632341        -0.504352        0.836317
                        0.130293        0.979892        0.0015135     0.000674112         0.138439      -0.0533728     -0.000494322      0.00106748
                      0.00188275     0.000244311        -0.503762        0.835776     -0.000627182       0.0010439         0.157939       -0.146372
281800                  0.146953       0.0110587      0.000649405     -0.00141699         0.141854        0.978388       0.00177875     0.000335458
                     0.000575314     -0.00143311       -0.0518127        0.206669       0.00174814     0.000615483        -0.495341        0.842257
                        0.141288         0.97848       0.00152622     0.000656152         0.138087      -0.0522115     -0.000485501      0.00108029
                      0.00188849     0.000221813        -0.494737        0.841709     -0.000614056      0.00105515          0.15552       -0.145745
[End]