! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:04 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=130; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.113857        0.172981      2.81873e-06    -8.62367e-06         0.580364       -0.787638      0.000281415    -1.35277e-05
                     5.92334e-05     2.14626e-05        -0.165312       -0.157747      0.000425834     0.000270169        -0.305181        -0.92433
                        0.580374       -0.787514      0.000267895      0.00011356         0.131574       -0.159943      6.00611e-05    -3.20263e-06
                     0.000317426    -6.99128e-05        -0.305128        -0.92436     -9.19324e-05    -0.000191737       -0.0386896        0.225212
281800                 -0.111443        0.172758      4.10184e-06    -9.93648e-06         0.574905       -0.792026      0.000280166    -1.62379e-05
                     5.81085e-05     2.14836e-05        -0.167634        -0.15918      0.000428146     0.000269241        -0.313237       -0.920966
                        0.574912       -0.791907       0.00026893     0.000111948         0.129808       -0.159445      5.91739e-05    -1.58247e-06
                     0.000315724    -7.44855e-05        -0.313185       -0.920996      -9.0487e-05    -0.000184324       -0.0356195        0.228422
[End]