! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:07:25 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=160; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.385728       -0.262568      -0.00079132     0.000161814          0.77089         -0.4333       0.00021711    -0.000141225
                    -0.000819593     0.000119524        -0.268318       -0.414422     -0.000669043    -1.46896e-05         0.858524       -0.137706
                        0.770699       -0.433323     -0.000733569    -1.53877e-05       -0.0240274       -0.465765      0.000562653    -0.000397473
                     0.000178027    -0.000276035         0.858595       -0.137592      0.000496441    -0.000409216         0.124976       -0.477424
281800                 -0.385733       -0.261584     -0.000794307     0.000165077         0.767175       -0.440428      0.000226814    -0.000132032
                    -0.000822333     0.000122815         -0.26949       -0.413106     -0.000670239    -7.78782e-06         0.857587        -0.14498
                        0.766982       -0.440473     -0.000735688      -6.851e-06       -0.0316333       -0.464758      0.000560258    -0.000409999
                     0.000176541    -0.000274709          0.85767       -0.144868       0.00049324    -0.000417265         0.118447       -0.478603
[End]