! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:09:17 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=180; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.221563       -0.172727      0.000243201      0.00014267        -0.536334       -0.795563     -0.000605519     0.000365597
                     0.000221294     9.13337e-05         0.461079       -0.295345      0.000506598    -0.000380578         0.548699        0.631056
                       -0.536258        -0.79568      0.000465405    -0.000406066        0.0771099         0.27019     -4.72768e-05     9.55735e-05
                    -0.000489223     0.000285831         0.548754        0.631124     -3.87374e-05    -4.42203e-05         0.356965       -0.415522
281800                 -0.224594       -0.172829      0.000245853     0.000135054        -0.543128       -0.790053     -0.000605848     0.000373029
                      0.00011908     0.000156139          0.45694       -0.298919      0.000498091    -0.000388661         0.555497        0.626413
                       -0.542973       -0.790116      0.000462391     -0.00041092        0.0810318        0.271641     -4.80478e-05     9.82046e-05
                     -0.00049637      0.00028662         0.555558        0.626484     -4.03015e-05    -4.56496e-05         0.351834       -0.417874
[End]