! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:54 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=190; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.321317        0.476934     -0.000290379    -0.000564026        -0.237288        0.782304      0.000161098      0.00015761
                    -0.000193224    -0.000572336       -0.0659467       -0.477071     -0.000233039     -7.2182e-05         0.875206      -0.0407444
                       -0.237332         0.78247     -0.000108463    -4.67651e-05         0.532394       -0.217929      0.000370865     0.000341511
                     0.000217146        0.000212         0.875172       -0.040912      0.000370508     0.000248089        0.0215049       -0.481104
281800                  0.325797        0.472357     -0.000294201    -0.000556468        -0.229594        0.785517      0.000157922     0.000159686
                    -0.000197575    -0.000571292       -0.0680663       -0.475583     -0.000231215    -6.96513e-05         0.875411      -0.0493522
                       -0.229635        0.785686     -9.95307e-05    -5.04044e-05         0.529175       -0.222406      0.000376992     0.000342215
                     0.000221383     0.000208903         0.875381      -0.0495303      0.000373919     0.000243853        0.0143476       -0.480191
[End]