! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:53 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=150; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.248188        0.289805     -8.93639e-05     0.000150977         0.780839        -0.49449     -0.000910363    -0.000100358
                    -7.82118e-05     9.65617e-05        -0.962088      0.00959455      6.07153e-05    -0.000128657         0.212193        0.161004
                        0.780643        -0.49435     -8.89307e-05     3.66588e-05         0.368088       -0.100103      0.000130097    -0.000258216
                     -0.00055852    -0.000270841         0.211799        0.160845      0.000305329     8.94996e-05          0.23388        0.932253
281800                 -0.244503        0.290213     -9.38171e-05     0.000155983         0.777009       -0.502053     -0.000872289    -4.62131e-05
                    -8.86835e-05     0.000115284        -0.954502       0.0326052      5.98828e-05    -0.000123876         0.237526        0.167928
                        0.776824       -0.501913     -8.75937e-05     4.52034e-05         0.365059       -0.103267      9.59738e-05    -0.000184612
                     -0.00056754    -0.000231261         0.237103        0.167767      0.000317986     0.000100358         0.273433        0.914071
[End]