! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:35 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=130; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0439052       -0.241354     -0.000126241      -0.0003526         0.768451        0.591006      0.000446258    -0.000927382
                    -4.27578e-05    -0.000729322      -0.00200956       -0.232517      0.000589454    -0.000596423         0.730478        0.641925
                        0.768343        0.590949      0.000527207     -0.00056882         0.244539      -0.0195343      0.000416709    -0.000358193
                     0.000440858    -0.000702731          0.73051        0.641948       0.00044256    -0.000281541         0.230831      -0.0279009
281800                -0.0462523        -0.24095     -0.000121542    -0.000339001          0.77243         0.58578      0.000439778    -0.000930786
                     -4.9346e-05    -0.000730362      -0.00437466       -0.232432      0.000586494    -0.000601049         0.734801        0.636993
                        0.772321        0.585723      0.000526914     -0.00057205         0.244496      -0.0204764      0.000412369    -0.000361321
                     0.000438611    -0.000709024         0.734832        0.637015      0.000440248    -0.000284765         0.230687      -0.0286587
[End]