! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:18 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=110; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.301368       -0.160352      0.000294092     7.53401e-05         0.915303        0.213931      0.000240702     -8.8059e-05
                     0.000118459     5.92868e-05        0.0518463       -0.221342        1.125e-05    -0.000109704         0.688513        0.688488
                        0.915267        0.213878      1.95696e-05    -0.000208269         0.341106      -0.0101551      -0.00018796    -0.000293571
                     0.000131438     -0.00013168         0.688735        0.688653     -0.000330726    -0.000233794         0.221316      -0.0518412
281800                 -0.302544       -0.158228      0.000298039     7.55542e-05         0.916747        0.207563       0.00024248    -8.80397e-05
                     0.000120275     6.04892e-05        0.0495166       -0.221613      9.58228e-06    -0.000112599         0.693177        0.683917
                        0.916717        0.207518      1.93229e-05     -0.00021171         0.341078      -0.0124648     -0.000193117     -0.00029576
                     0.000130707     -0.00013188         0.693376        0.684069     -0.000332878    -0.000231902         0.220903      -0.0524757
[End]