! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:20 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=110; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.243588        0.962127      0.000288692     0.000148304       -0.0760617       0.0931916     -0.000158157     0.000176307
                     0.000282758     0.000226633        -0.722121       -0.226376      0.000185927      0.00016723        -0.272779       -0.593612
                      -0.0757649        0.093563        2.067e-05     0.000379823         0.991524       0.0459647      0.000383787    -0.000226433
                    -0.000423119     4.66531e-05        -0.272897       -0.593719      0.000257322    -0.000122732        -0.297862        0.695531
281800                  0.249293        0.960595      0.000300384     0.000154685       -0.0756915        0.094201     -0.000155806     0.000178506
                      0.00028093     0.000226415        -0.725072       -0.223655      0.000185243     0.000168251        -0.278099       -0.588561
                      -0.0753917       0.0945639       3.2743e-05     0.000358676         0.991842       0.0367208       0.00038125    -0.000231882
                    -0.000420587     5.89056e-05        -0.278196       -0.588672      0.000259876    -0.000125536         -0.28694        0.702279
[End]