! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:01:07 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=120; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.213084       -0.431807     -0.000187653    -0.000581027         0.797615        -0.36291     -0.000574408    -0.000485096
                    -0.000137107    -0.000605273        -0.161438       -0.363788     -0.000388552    -0.000478464         0.897047       -0.191481
                        0.797554       -0.362842     -0.000410111     -0.00047454        -0.185679       -0.444082     -0.000892277    -0.000486839
                    -0.000577656    -0.000433511         0.897218       -0.191558     -0.000877542    -0.000462598      -0.00130379       -0.397888
281800                 -0.213557       -0.431124     -0.000189169    -0.000584196         0.794528       -0.370137     -0.000581347    -0.000484112
                    -0.000138318    -0.000609708         -0.16185       -0.362436     -0.000394653    -0.000479579         0.895931       -0.198777
                        0.794475       -0.370073     -0.000416907    -0.000473667        -0.192784       -0.440603     -0.000905079    -0.000477208
                    -0.000584353    -0.000431185         0.896103       -0.198857     -0.000888434     -0.00045384      -0.00674889       -0.396765
[End]