! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=150; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.788318        0.559979      0.000879871      0.00152065         0.246413       0.0633293      0.000405647     1.29311e-05
                     0.000758731      0.00131638        -0.921527        0.299065      2.71329e-05    -0.000149283         0.206726        0.135443
                        0.246504       0.0633373      6.09167e-05     8.98709e-05         0.420794        0.870572      0.000346706    -0.000153337
                     0.000663711    -7.00334e-05         0.206622        0.135198      0.000229266    -0.000139714        0.0937301        0.964238
281800                  -0.78606        0.563142      0.000886534      0.00151102         0.246889       0.0614638      0.000406724     9.13532e-06
                     0.000763997      0.00131464        -0.920218         0.30282      3.09283e-05    -0.000148317         0.208122        0.133837
                         0.24698       0.0614772       6.4667e-05     6.84181e-05         0.430411        0.865856      0.000351703    -0.000154693
                     0.000661889    -7.89182e-05         0.208024        0.133603      0.000233184    -0.000139605         0.106185        0.962871
[End]