! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:31 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=190; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.142899       -0.090385       8.2245e-05     0.000209658        -0.393348       -0.903562     -5.56543e-05    -0.000248765
                      0.00010766     0.000106773        -0.146487       -0.262818      -0.00022573    -9.31389e-05         0.943628        0.134717
                       -0.393425       -0.903678      -0.00025962     2.56263e-05          0.16359       -0.043009      8.27825e-05     4.12902e-05
                     3.54317e-05    -0.000182926         0.943599        0.134745      0.000166541     2.59143e-05         0.214116       -0.211384
281800                  0.141248      -0.0924354      8.03023e-05     0.000207682        -0.400189       -0.900606     -5.87714e-05    -0.000251465
                     0.000106933     0.000104825        -0.148332       -0.260681      -0.00022817    -9.06227e-05         0.945221        0.125332
                       -0.400266       -0.900719      -0.00026134       2.916e-05         0.163336      -0.0428771      8.14408e-05     4.20413e-05
                     3.30829e-05    -0.000186444         0.945194        0.125358       0.00016592     2.62523e-05          0.21108       -0.213068
[End]