! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:48 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=130; L_y=160; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.156532       -0.255729      -0.00032273    -0.000279315         0.873679        0.383011      0.000225311    -0.000374723
                    -0.000369487    -0.000227525       -0.0173744       -0.256721      8.83012e-05    -0.000552204          0.77787        0.573395
                        0.873647        0.383052      9.93298e-05    -0.000451361         0.294082      -0.0581458        0.0003744     4.56271e-05
                      0.00018779    -0.000445955         0.777871         0.57344      0.000413871    -5.15245e-05         0.250355      -0.0594327
281800                 -0.158482       -0.254414     -0.000323638    -0.000273598         0.876344         0.37695      0.000224153    -0.000378067
                    -0.000369792    -0.000222052       -0.0197008       -0.256368      8.29137e-05    -0.000552792         0.781793         0.56812
                        0.876311        0.376991      9.68485e-05    -0.000449943         0.293633      -0.0599021      0.000373906     4.24446e-05
                     0.000184647    -0.000447456          0.78179        0.568165      0.000412249    -5.58516e-05         0.249907      -0.0605116
[End]