! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:53 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=170; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.911336       -0.399077      5.50228e-05     0.000526738       -0.0286351      -0.0938288      0.000372866    -0.000791002
                     6.18231e-05     0.000541227        -0.198281       -0.484876      0.000387078     0.000165515         0.657285       -0.541431
                      -0.0288707      -0.0936814      0.000441542     0.000156008        -0.525614        0.844448     -0.000125129    -0.000987939
                     0.000271059    -0.000791432         0.657356       -0.541257     -5.52399e-05    -0.000679539        -0.437381       -0.287341
281800                 -0.914396       -0.393095      6.90339e-05     0.000534146       -0.0285576      -0.0892199      0.000375363    -0.000823925
                     7.52737e-05     0.000551916        -0.198253       -0.485249      0.000389791     0.000156925          0.64951       -0.550413
                      -0.0287873      -0.0890684      0.000449325     0.000143469        -0.508249         0.85551     -0.000154257    -0.000995657
                     0.000269113    -0.000821671         0.649581       -0.550232     -6.11155e-05    -0.000677909        -0.445567       -0.275055
[End]