! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:01:16 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=120; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0465131        -0.23887       0.00020287    -0.000200847         0.786596        0.566681       0.00107778     3.90579e-05
                    -9.55084e-05    -0.000269566        0.0674459        0.118742      0.000668267    -0.000705561        -0.174723        0.975008
                        0.786725        0.566614      0.000722803    -0.000814448         0.241427      -0.0316381      0.000274523    -1.20696e-05
                      0.00088604     4.16253e-05        -0.174697        0.974737      0.000250716    -3.87988e-05         0.104784      -0.0879661
281800                -0.0502049       -0.238422      0.000136653         -0.0002         0.792159        0.558763       0.00108344     3.18052e-05
                    -9.21034e-05    -0.000266889        0.0695301         0.11518       0.00066213    -0.000717948        -0.163726        0.977219
                        0.792277        0.558699      0.000728615    -0.000813565         0.241563      -0.0328186      0.000283146    -2.23115e-05
                     0.000889402     3.38302e-05        -0.163703        0.976926      0.000257236    -3.57786e-05         0.103576      -0.0862626
[End]