! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:38 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=130; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.790973        0.606246     -3.79137e-05    -8.77499e-05       -0.0794631     -0.00914723     -2.92996e-05     1.54668e-06
                     -4.6906e-05    -0.000110657        -0.922638        0.314454       0.00011436    -0.000147035        -0.200941      -0.0946735
                      -0.0794077     -0.00924471      8.32469e-05     1.81831e-05         0.633334        0.769416      0.000100943     0.000116401
                     -0.00015693    -3.60404e-05        -0.200883      -0.0946884     -0.000214864    -0.000291817         0.345999        0.911264
281800                  -0.78787         0.61039     -3.86629e-05    -8.65795e-05       -0.0786345     -0.00839134     -2.81692e-05     7.95021e-08
                     -4.8323e-05     -0.00010831        -0.921318        0.319544      0.000107873    -0.000146321        -0.200176      -0.0920678
                      -0.0785804     -0.00848685      8.32266e-05     1.70149e-05         0.642098        0.762215      0.000100148     0.000108213
                    -0.000153494    -2.96954e-05         -0.20012      -0.0920844     -0.000223591    -0.000275035         0.358015        0.907049
[End]