! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:29 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=150; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.233435       -0.151166     -0.000459736    -0.000440838         0.959534      -0.0384329      3.96726e-05      0.00151812
                    -0.000280134    -0.000324139        -0.227555       -0.137661      0.000195028      0.00151893         0.916332       -0.298881
                        0.959618       -0.038576      0.000178886      0.00145441         0.220548       -0.169415      0.000943788     6.84171e-05
                     0.000132811      0.00153113         0.916181       -0.299144      0.000875211     9.99639e-05         0.102512       -0.245315
281800                 -0.233828       -0.148483     -0.000462501    -0.000438496         0.959463       -0.047248      5.17694e-05      0.00152032
                      -0.0002884    -0.000317651        -0.226665       -0.135865      0.000208879      0.00152301         0.913841       -0.307886
                        0.959548      -0.0473722      0.000194503      0.00145991         0.218061       -0.170796      0.000955192     5.76344e-05
                     0.000147447       0.0015326         0.913697       -0.308139      0.000881369     9.01099e-05        0.0981171        -0.24528
[End]