! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:56:46 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=90; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0421612        0.134604      0.000247418      0.00047496        -0.211613        0.967135     -0.000290727    -0.000350508
                     0.000203942     0.000436397         0.054107        0.179572     -0.000371661    -4.99325e-06        -0.256695         0.94818
                       -0.211668        0.967112     -0.000384579     4.54856e-05        0.0945228       -0.104711      0.000460699    -0.000301909
                    -0.000299258    -0.000348152         -0.25677        0.948204        0.0004847    -0.000265653         0.137288       -0.127741
281800                 0.0432355        0.132791      0.000250388     0.000474242        -0.205296          0.9687     -0.000294649    -0.000349044
                     0.000206814     0.000436682        0.0554418        0.177854     -0.000373005    -2.12361e-06        -0.250614        0.950051
                       -0.205351        0.968671     -0.000384687     4.83243e-05        0.0933849       -0.103851      0.000457294     -0.00030733
                    -0.000303329    -0.000346131         -0.25069        0.950076      0.000482643    -0.000271601         0.135937       -0.127354
[End]