! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:45 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=150; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.260225      -0.0969865     -6.84922e-05    -0.000211975         0.947272       -0.158879     -0.000168794    -0.000171728
                    -7.82423e-06    -0.000311565        -0.255994       -0.207344     -0.000288681    -0.000190831         0.359856       -0.872576
                        0.947445       -0.158957     -0.000236729    -0.000144517         0.214348       -0.176585      -0.00030852    -9.47278e-05
                    -0.000144819    -0.000177532         0.360066       -0.872633     -0.000304341     5.89051e-05        -0.327578      -0.0332254
281800                 -0.259924      -0.0945734     -7.06226e-05    -0.000213259         0.946487       -0.165318     -0.000170433    -0.000169704
                    -1.14707e-05    -0.000314082        -0.255919       -0.208576     -0.000291543    -0.000187229         0.351575       -0.875673
                        0.946669       -0.165392     -0.000238185    -0.000142357         0.212483       -0.177083     -0.000309919    -9.23298e-05
                    -0.000146551    -0.000176017         0.351785       -0.875731     -0.000301334     6.21591e-05        -0.328941      -0.0261409
[End]