! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:30 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=140; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.313861       -0.220747     -0.000120572     -3.7582e-05         0.918988      -0.0899663     -0.000179818    -0.000183216
                    -0.000106629     1.78124e-05       -0.0976037       -0.332071      0.000139805    -0.000223627         0.885055        0.310982
                        0.918991      -0.0899797      0.000224727    -0.000180201         0.264915       -0.277382     -1.28217e-05    -6.04782e-05
                     -0.00017941    -0.000175492         0.885061         0.31108      9.49913e-05    -0.000112892         0.283752       -0.198008
281800                 -0.314232       -0.218874     -0.000131988    -3.17557e-05         0.918586      -0.0970999     -0.000187533    -0.000223495
                    -0.000104978     1.90095e-05       -0.0995449       -0.330961      0.000136181    -0.000224183         0.887476        0.304728
                        0.918594      -0.0971094      0.000220702    -0.000188156         0.261349       -0.279686      1.97116e-05    -7.53698e-05
                    -0.000179473     -0.00017648         0.887462        0.304774      9.00209e-05     -0.00011602         0.281731       -0.199996
[End]