! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:57 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=150; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.876974        0.105095      -0.00021774     0.000970028         0.106098        0.456031     -0.000437165    -0.000343015
                     7.34095e-05     0.000821789         0.569309        0.716394     -0.000275917    -0.000875768        -0.134901        0.379147
                        0.106035        0.455978     -0.000294101    -0.000871487         0.740931        -0.48102      0.000694701     0.000830064
                    -0.000399013    -0.000406871        -0.134794         0.37925      0.000730931     0.000857414         0.894165       -0.195112
281800                  0.877012       0.0985277     -0.000207048     0.000974592          0.11041          0.4564     -0.000441928    -0.000339763
                     7.92764e-05     0.000817911         0.574042        0.711741     -0.000284476    -0.000876792        -0.132178        0.381725
                        0.110348        0.456343      -0.00030305    -0.000871464         0.735419       -0.488106      0.000704282     0.000823414
                    -0.000401895    -0.000401513        -0.132067        0.381828      0.000739426     0.000850165         0.891559       -0.203685
[End]