! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:55:53 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=80; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.302196       -0.370085     -0.000253939    -1.29005e-05         0.665777         -0.5729     -0.000216448    -0.000211628
                      -0.0002393    -3.38687e-05       -0.0696777       -0.265906       4.6259e-05    -7.32589e-05         0.896482        0.347412
                        0.665775       -0.572799      6.71075e-05    -0.000176321        -0.320971       -0.353631      0.000164635    -8.16157e-05
                    -0.000250746    -0.000144321         0.896478        0.347382      0.000121808    -7.18483e-05         0.230663       -0.149517
281800                 -0.302447       -0.370009     -0.000252865     -1.1857e-05         0.660164       -0.579267     -0.000218784    -0.000208823
                    -0.000237975    -3.16534e-05       -0.0715852       -0.264467      4.50886e-05    -7.23816e-05          0.89901         0.34154
                        0.660166       -0.579168      6.71757e-05    -0.000178859        -0.327636       -0.347598      0.000160716    -8.27974e-05
                    -0.000252916    -0.000142619         0.899005        0.341512      0.000118738    -7.21984e-05         0.229128       -0.150225
[End]