! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:54:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=70; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750               -0.00301688       -0.285412     -2.48176e-05     0.000417164         0.829372        0.479524      0.000327789     0.000191912
                    -7.03506e-05     0.000405334         0.166643       0.0404225      6.62994e-05     0.000484798        -0.129854        -0.97654
                        0.829551        0.479412      6.77343e-05     0.000546342         0.248909       -0.139872      0.000400126      3.4781e-05
                     0.000263332     0.000157166        -0.129813       -0.976489       0.00042296     3.69863e-05         0.150288      -0.0825386
281800               -0.00657343       -0.284999     -2.71399e-05     0.000417037          0.83433        0.471061      0.000327954      0.00018979
                    -7.17607e-05     0.000408258         0.166388       0.0378935      7.20475e-05     0.000485267        -0.136996       -0.975707
                        0.834511        0.470945      7.13656e-05     0.000545661         0.247477       -0.141678      0.000402075     2.95593e-05
                     0.000265583     0.000159907        -0.136955       -0.975656      0.000425773      3.1829e-05         0.149518      -0.0822214
[End]