! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:50 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=170; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.421512       -0.291329      0.000211362     -0.00017974         0.681981       -0.521546     -0.000442005    -0.000828067
                     0.000195477    -0.000179254        -0.362575       -0.418473     -0.000368786    -0.000790997         0.765895       -0.326309
                        0.682158       -0.521619     -0.000385572    -0.000768222        -0.170883       -0.482742      -0.00127197       0.0003594
                    -0.000418704    -0.000794731         0.766098       -0.326286      -0.00126369     0.000367309       -0.0508634       -0.551148
281800                 -0.421798       -0.290626      0.000209923    -0.000183985         0.676992       -0.528161      -0.00045477     -0.00082567
                     0.000194337    -0.000184145        -0.363606       -0.417312     -0.000380365    -0.000789973         0.762968       -0.333424
                        0.677166       -0.528235     -0.000396941    -0.000766787        -0.179418        -0.47946      -0.00127338     0.000379385
                    -0.000431189    -0.000792224         0.763177       -0.333403      -0.00126525     0.000386513       -0.0594881        -0.55008
[End]