! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:53:46 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=70; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.188453      -0.0788796      0.000267517     0.000161022         0.384877        0.899696     -0.000219579    -3.26991e-05
                     0.000223181    -8.19602e-05         0.228275      -0.0381887     -0.000106146    -1.72585e-05         0.318969        0.918633
                        0.385072        0.900039     -0.000242089    -5.36573e-05         0.187182      -0.0818446      0.000238605     2.07528e-05
                    -0.000139565     3.58119e-05         0.319242        0.919172      0.000208444     2.20735e-05         0.202805       -0.111491
281800                  0.186942      -0.0806406      0.000272652     0.000157873         0.390794        0.897302     -0.000219003    -3.16817e-05
                     0.000223091    -8.54767e-05         0.227074      -0.0401917      -0.00010707    -1.48627e-05         0.324968        0.916751
                        0.390988        0.897644     -0.000243681    -5.10745e-05         0.186359      -0.0819718      0.000240087     1.81546e-05
                    -0.000139956     3.74963e-05         0.325238        0.917282      0.000209099     1.91014e-05         0.201677       -0.111789
[End]