! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:31 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=120; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                0.00401289       -0.267798     -4.60596e-05    -0.000296645         0.821845        0.502832     -0.000101766    -2.00366e-05
                     -4.0273e-05    -0.000271704        -0.112767       -0.250539     -9.56618e-05      -9.371e-05         0.914756        0.295899
                        0.821827        0.502834     -8.90302e-05    -9.11763e-05          0.23659       -0.125469      0.000247984     -0.00014676
                    -3.22579e-05     -6.8611e-05         0.914917        0.295891      0.000242439    -0.000150247         0.238132       -0.137023
281800                0.00171639       -0.267042     -4.86576e-05    -0.000296137         0.825298        0.497566     -0.000101537    -1.86698e-05
                    -4.28488e-05    -0.000271653        -0.114484       -0.248865     -9.61711e-05    -9.28542e-05         0.916933        0.289848
                        0.825279        0.497569     -8.97606e-05     -9.0147e-05         0.235335       -0.126165       0.00024749    -0.000147579
                    -3.25882e-05     -6.7803e-05         0.917097        0.289841      0.000242128    -0.000151274         0.236722       -0.137836
[End]