! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:18 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=150; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750               -0.00253079       0.0286785      4.17708e-06    -0.000372544       -0.0769548        0.996683      0.000271653     -0.00024241
                    -0.000110627    -0.000453246       -0.0346709      -0.0151557      0.000231715     0.000292692        -0.020017        0.999264
                      -0.0768825        0.996649      0.000253106     0.000171072       0.00193958      -0.0287003     -0.000125575     0.000454596
                     0.000267272    -0.000207591       -0.0199794        0.998852     -0.000185274     0.000523493       -0.0352463       0.0137454
281800               -0.00220896       0.0267569      6.81808e-07    -0.000376253       -0.0701861        0.997236      0.000270567     -0.00024573
                    -0.000114484    -0.000451801       -0.0346877      -0.0170358      0.000232748      0.00029037       -0.0131326         0.99935
                      -0.0701133          0.9972       0.00025389      0.00016956       0.00159854       -0.026776     -0.000121921     0.000456883
                     0.000266983    -0.000210199       -0.0130973        0.998936       -0.0001816     0.000525761       -0.0351196       0.0161086
[End]