! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:41 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=170; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.22424        -0.50051     -8.82224e-05    -0.000732986         0.673074       -0.495829     -0.000546786     -0.00032215
                    -7.24095e-05    -0.000727665        -0.162007       -0.412387     -0.000671888    -0.000222557          0.83213       -0.333085
                        0.673071       -0.495741     -0.000663726    -0.000235504        -0.411494       -0.362342      -0.00108825    -0.000118386
                    -0.000545663    -0.000316502         0.832023       -0.333106      -0.00105579    -9.77351e-05        -0.167279       -0.410175
281800                 -0.225406       -0.500678     -9.45367e-05    -0.000735032         0.667037       -0.503231     -0.000555029    -0.000317163
                    -7.77744e-05    -0.000728064        -0.162497       -0.411526     -0.000677396    -0.000215546            0.829       -0.341598
                        0.667039       -0.503142     -0.000668766    -0.000229505        -0.419503       -0.354016      -0.00109217    -0.000100972
                    -0.000550701    -0.000311665         0.828897        -0.34161      -0.00105919     -8.1784e-05        -0.174579       -0.406439
[End]