! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:12:14 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=200; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                0.00379364       -0.265196     -0.000258486    -0.000130039         0.781446        0.564739     -0.000134618     0.000201453
                    -0.000290854    -8.97329e-05        -0.338325       -0.127449     -0.000213748     0.000344372         0.932267       0.0057973
                        0.781651          0.5646     -0.000229079     0.000265423         0.250554      -0.0868777      0.000304214     0.000231939
                     -0.00018764     0.000207506         0.932358      0.00562678      0.000317778     0.000269718         0.339785       -0.123248
281800                 0.0014833       -0.264879     -0.000258365    -0.000127674         0.785349        0.559459     -0.000134281     0.000203798
                      -0.0002909    -8.83863e-05        -0.338656       -0.125205     -0.000211956     0.000346676         0.932467    -0.000955556
                        0.785556        0.559318     -0.000227013     0.000267834         0.249804      -0.0879963      0.000306037     0.000228903
                    -0.000185837     0.000210665         0.932555     -0.00112694      0.000320464     0.000267336           0.3383       -0.125915
[End]