! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:53:57 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=70; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0473831        0.163091      0.000484772    -0.000104885        -0.244673        0.954609       6.6585e-06    -1.59897e-05
                     0.000467655    -0.000153889        0.0569164        0.221427      5.94904e-05     0.000103017        -0.300918        0.925757
                       -0.244726        0.954651      6.27085e-06     1.19906e-05         0.120053       -0.120138       0.00026057     0.000419814
                     2.26725e-05    -4.64918e-05        -0.301066        0.925797      0.000298122      0.00039778         0.176289        -0.14559
281800                 0.0486383         0.16135      0.000487528    -0.000112086        -0.238507        0.956399      6.40757e-06    -1.75992e-05
                     0.000470427    -0.000156648        0.0584847        0.219844      6.13099e-05     0.000101916        -0.295086        0.927911
                        -0.23856        0.956445      7.09732e-06      1.2112e-05         0.118768       -0.119564       0.00026445     0.000419926
                     2.25695e-05    -4.70439e-05        -0.295235        0.927952      0.000302114     0.000397747         0.174782        -0.14563
[End]