! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:57:24 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=90; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.218082       -0.187522      -1.7091e-05    -0.000361802         0.832795        0.473112      5.42921e-06     0.000109869
                     0.000154812    -0.000353238          0.13434       -0.145095       3.8965e-05    -0.000154972          0.52449        0.828498
                        0.832807         0.47304      -1.5234e-05    -0.000332859         0.272737       0.0912551      0.000348209    -0.000166085
                     2.31432e-05     1.96669e-05         0.524266        0.828338      0.000285812    -9.95597e-05         0.188648      -0.0593434
281800                 -0.220129       -0.186138     -2.15318e-05    -0.000360378         0.835799        0.467383      7.11309e-06     0.000111049
                     0.000149862    -0.000353048         0.132341        -0.14628       3.6405e-05    -0.000155789         0.529986        0.825102
                        0.835808        0.467306     -2.16105e-05    -0.000333506         0.273839       0.0900322      0.000347088    -0.000166288
                     2.20084e-05     1.94574e-05         0.529768        0.824943      0.000286256    -9.95426e-05         0.188096      -0.0595126
[End]