! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:08:51 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=170; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.476641        0.859415     -0.000760871    -0.000482122         0.181331      -0.0322657      0.000194569    -4.65963e-05
                    -0.000734714    -0.000472565         -0.59834        0.789264      3.39411e-05     7.06766e-05         0.136386     -0.00555264
                        0.181343      -0.0321801     -9.38864e-06     0.000105244         0.743911        0.642236     -4.04259e-06       0.0007002
                    -2.80796e-05      0.00012723         0.136464     -0.00573026     -0.000157949     6.84643e-05         0.661994        0.736703
281800                 -0.472806        0.861563      -0.00076463    -0.000480469         0.180947      -0.0335281      0.000188325    -5.21303e-05
                    -0.000739085    -0.000470501        -0.594445        0.792355      3.42896e-05     7.03031e-05         0.135439      -0.0065869
                        0.180956      -0.0334418     -7.92294e-06     0.000102911         0.750168        0.634962     -8.31828e-06     0.000693888
                    -2.74645e-05     0.000130353         0.135518     -0.00676769     -0.000165102      7.0755e-05         0.670025        0.729577
[End]