! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:24 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=140; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                   0.18697      -0.0874942      -6.7264e-05    -7.54597e-05         0.410694        0.888179      6.24103e-05     3.38305e-05
                     0.000160716     9.64078e-05        0.0347532       -0.179197     -0.000276143     0.000242005         0.603746        0.775855
                        0.410413        0.888315      -2.5645e-05    -3.21407e-05         0.187766      -0.0856856     -3.56334e-05     2.48654e-05
                     -8.5895e-05     2.76019e-05         0.604129        0.775609      -1.4055e-05    -4.45681e-05          0.18226       0.0102295
281800                  0.185378        -0.08918     -6.71641e-05    -7.39491e-05         0.416545        0.885613      6.11084e-05     3.44427e-05
                     0.000165302     9.38745e-05        0.0324935       -0.179815     -0.000290856     0.000245841         0.608881        0.771788
                         0.41627        0.885756     -2.67458e-05    -3.21804e-05         0.186914      -0.0858293      -3.5635e-05     2.40777e-05
                    -8.74835e-05     2.76953e-05         0.609264        0.771538     -1.24489e-05     -4.8136e-05         0.182455        0.010141
[End]