! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:34 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=120; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.128452        0.169253     -4.39366e-05     -0.00017271          0.13716       -0.967501     -0.000428618     9.65003e-05
                     0.000124696    -0.000497157        0.0554896       -0.155278     -0.000470637     6.11831e-05        -0.517079       -0.839846
                        0.137169       -0.967462     -0.000440432    -2.94278e-05         0.170403       -0.126869      2.69284e-05      0.00025789
                    -0.000550832     0.000137819         -0.51717       -0.839765     -9.28849e-05     0.000214055         0.163698       0.0203242
281800                  0.129609        0.166985     -4.73417e-05    -0.000169937         0.130324       -0.968688     -0.000428217      0.00010113
                     0.000114742    -0.000498611         0.053079       -0.156665      -0.00047291     6.92707e-05          -0.5236       -0.835688
                        0.130335       -0.968647     -0.000439871    -2.54546e-05         0.169102       -0.126781      3.24498e-05     0.000255551
                    -0.000549594     0.000145286        -0.523691        -0.83561     -8.83528e-05     0.000214337         0.164194       0.0205301
[End]