! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:45 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=140; L_y=110; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.357794       -0.151605      5.26648e-06    -0.000546293        -0.631493       -0.670598      2.84983e-05     0.000202877
                     3.83281e-05     -0.00059926       -0.0813261        0.766691     -0.000417027    -3.90771e-05        -0.479258         0.41827
                       -0.631422       -0.670566     -0.000501052    -1.19688e-05         0.130114        0.366205      0.000219773    -0.000656433
                     0.000109556     0.000217399        -0.479401        0.418456      0.000245888    -0.000796072         0.770784       0.0231695
281800                 -0.361104       -0.150214      5.35588e-07    -0.000548752         -0.63703       -0.663865      2.95142e-05     0.000202266
                     3.28156e-05    -0.000601739       -0.0747154        0.767194     -0.000420176    -3.36167e-05        -0.475465        0.422881
                       -0.636959       -0.663832     -0.000504552    -3.69142e-06         0.135449        0.366946      0.000212343     -0.00065954
                      0.00011238      0.00021663        -0.475606         0.42307      0.000237128    -0.000800479         0.770812       0.0153338
[End]