! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:07:29 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=160; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0756354        0.109219     -6.01412e-05    -0.000512388         0.453752       -0.880914     -0.000493308    -0.000760422
                    -9.23093e-05    -0.000503784        -0.185361        0.221133     -0.000713951    -0.000391709         0.725622       -0.624082
                        0.453879       -0.880865     -0.000671699    -0.000364934        0.0452197       -0.124743     -0.000773873    -0.000216991
                    -0.000504295    -0.000785301         0.725664       -0.624138      -0.00076957    -0.000184907         0.246539       -0.150028
281800                -0.0735851        0.107176     -6.65084e-05    -0.000511717         0.445894        -0.88535     -0.000499755    -0.000756218
                    -9.75704e-05     -0.00050248        -0.181543        0.222024     -0.000713744    -0.000383304         0.720009       -0.631354
                        0.446013       -0.885295     -0.000675828    -0.000358521        0.0425163       -0.122682     -0.000771847    -0.000208502
                    -0.000511841    -0.000779089         0.720035       -0.631411     -0.000763645    -0.000171716         0.244005       -0.150834
[End]