! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:54:17 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=70; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.196211       -0.220588     -0.000337167     -8.5168e-05         0.955223      -0.0261526      1.37771e-05    -1.03388e-05
                    -0.000310864     1.28812e-05       -0.0190687       -0.267762     -0.000183999     0.000124384         0.844612        0.463369
                        0.955106      -0.0262309     -2.41026e-05     0.000122384          0.18382        -0.23097      0.000244222     0.000131227
                    -0.000102594     -8.0704e-06         0.844565        0.463422      0.000181967     0.000101153         0.236072       -0.127844
281800                 -0.196682       -0.218498     -0.000336805    -8.38252e-05         0.955398      -0.0330045       1.1885e-05    -7.31327e-06
                     -0.00031045     1.52423e-05       -0.0212866       -0.266803     -0.000183168     0.000127969         0.847828        0.457931
                        0.955276      -0.0330773     -2.48095e-05     0.000122639         0.181108       -0.231526      0.000246911     0.000129448
                    -0.000102556    -7.30296e-06         0.847776        0.457985      0.000182197     0.000100573         0.234791       -0.128545
[End]