! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:59:02 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=100; L_y=200; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.136362         0.98641      7.89839e-05    -3.37803e-05       -0.0619385       0.0636063     -4.55428e-05     2.07689e-05
                     5.87734e-06     3.95227e-05        -0.278298       -0.241286      0.000129096     0.000451868         0.297622        -0.88061
                      -0.0617945       0.0637318      4.69465e-05      0.00035757         0.989492        0.112606      0.000525446      0.00017875
                    -7.12096e-07    -3.43181e-05         0.297735       -0.880535      0.000546407     0.000170507        -0.367524       0.0231781
281800                  0.142022         0.98559      7.93495e-05    -3.59481e-05       -0.0616266       0.0642385     -4.57243e-05     2.07391e-05
                      7.0882e-06     3.94145e-05        -0.278547       -0.242409      0.000134282     0.000449929         0.289111       -0.883054
                      -0.0614809       0.0643669      5.11194e-05     0.000357837         0.990469        0.103451      0.000525933     0.000171681
                    -5.10582e-07    -3.49043e-05         0.289226       -0.882979        0.0005473     0.000164107        -0.367882       0.0309308
[End]