! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:10:27 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=190; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.159838       -0.118531      0.000117424    -2.70798e-05         0.469577        0.859885      3.93495e-05     0.000194925
                     6.88756e-05      5.7174e-05        -0.249189       -0.166858     -8.51349e-05     1.17054e-05         0.826827        0.475499
                        0.469761        0.860028     -0.000128844     3.50217e-05         0.186107        -0.07043     -5.49183e-05     2.45774e-06
                    -9.03279e-05     0.000163774         0.826912        0.475687     -6.50896e-05    -0.000148805         0.269498         0.13153
281800                   0.15802       -0.119963      0.000118038    -2.80929e-05         0.475265        0.856892      4.14558e-05     0.000193066
                     7.07531e-05     5.47845e-05          -0.2512        -0.16538     -8.39737e-05     1.23994e-05         0.829767        0.469798
                        0.475447        0.857036     -0.000128637     3.56764e-05          0.18542      -0.0705635     -5.35763e-05     2.71946e-06
                    -8.88779e-05     0.000165289         0.829856        0.469985     -6.66402e-05    -0.000148184         0.271008        0.130381
[End]