! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:56:18 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=90; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.252841        -0.14311     -0.000234096     0.000170195         0.956097      -0.0391947      4.09906e-06     0.000205061
                    -0.000235149     0.000121185        -0.264681       -0.107215      -6.5773e-05     0.000209937         0.950134       -0.124692
                        0.956122      -0.0392011     -7.29962e-05     0.000235312         0.240315       -0.163296      0.000282573     0.000139964
                    -2.19155e-05     0.000216522         0.950309       -0.124732      0.000333479     0.000214563         0.228105       -0.171823
281800                 -0.253128       -0.140644     -0.000232954     0.000172085         0.956106      -0.0455435      5.29153e-06     0.000205849
                    -0.000234813     0.000123294        -0.264545       -0.104754     -6.36592e-05     0.000211369         0.949584       -0.131096
                        0.956132      -0.0455491     -7.15895e-05     0.000236369          0.23865       -0.164038      0.000283888     0.000137916
                    -2.07931e-05     0.000216855          0.94976       -0.131138       0.00033502     0.000211603         0.226318       -0.172458
[End]