! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:04:52 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=150; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0846738        0.159895     -5.68195e-05    -0.000261306         0.515424       -0.837632     -0.000378735     0.000122474
                    -8.46837e-05    -0.000304912        -0.640393        0.284026     -0.000106767    -3.46202e-05        -0.703833          -0.115
                        0.515306       -0.837443     -2.00623e-05     9.50599e-05          0.10457       -0.147633      0.000279423     0.000170725
                    -0.000285627     0.000216225        -0.703815       -0.115029      7.14883e-05     0.000334891         0.516922        0.472934
281800                -0.0823883        0.159265     -6.04245e-05    -0.000261263         0.509474       -0.841617     -0.000375592     0.000127346
                    -8.90736e-05    -0.000304561        -0.639647        0.289149     -0.000103856    -3.00881e-05        -0.703476       -0.108382
                        0.509355       -0.841421     -1.90042e-05     9.51552e-05         0.102911       -0.146821      0.000282353     0.000171957
                    -0.000284358     0.000221837        -0.703459        -0.10841      8.07885e-05     0.000329789         0.523187        0.468115
[End]