! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:54:22 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=70; L_y=160; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0411318       -0.192383      -0.00013109     0.000117639         0.659481        0.725326     -0.000119208     0.000233854
                    -4.75803e-05     0.000289667         0.200522      -0.0718409     -8.54228e-05     4.72367e-06         0.381049        0.899898
                         0.65957        0.725464      -0.00011476     1.47803e-05         0.187609       0.0591889     -0.000166381     2.20664e-05
                     2.42395e-05     0.000120439         0.380818        0.899745      -0.00021501     2.82385e-05         0.191146       -0.093912
281800                -0.0435093       -0.192522     -0.000131235     0.000120904         0.664229        0.720802     -0.000117686     0.000235092
                    -4.58573e-05     0.000290467         0.199052      -0.0736393     -8.58959e-05     6.63903e-06         0.386962        0.897555
                         0.66432         0.72094     -0.000114279     1.64347e-05          0.18833       0.0590547     -0.000167349     2.33987e-05
                     2.59287e-05     0.000120309         0.386727        0.897403     -0.000215518     2.88543e-05         0.190206      -0.0940861
[End]