! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:56:26 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=90; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.172984        0.174875       9.2689e-05     2.17611e-05         0.690673       -0.680045      2.68139e-05    -0.000210741
                     6.57201e-05     1.67938e-05        -0.144604        0.176443     -0.000159126     1.40955e-05         0.641671         -0.7323
                        0.690667        -0.68004     -0.000168544     2.12992e-05         0.177553       -0.170264     -3.93656e-06     3.51739e-05
                     3.86272e-05    -0.000208533         0.641695       -0.732189     -2.78696e-05     4.37098e-05         0.155907       -0.166579
281800                 -0.170581        0.175438      9.38701e-05      1.9555e-05         0.686165       -0.685053      2.54602e-05    -0.000211649
                     6.67075e-05     1.73126e-05        -0.142169        0.176635     -0.000159289     1.50038e-05          0.63671       -0.737046
                        0.686157       -0.685047     -0.000168712      2.3394e-05         0.175731        -0.17031     -3.97962e-06     3.54352e-05
                     3.72577e-05    -0.000209156         0.636734       -0.736936     -2.73023e-05     4.43144e-05         0.154091       -0.166376
[End]