! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:01:55 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=130; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.215712       -0.055929     -5.26046e-05    -4.17511e-05         0.350322        0.909667      2.00757e-05     3.99165e-05
                     1.54735e-05    -4.07141e-05        0.0987294       -0.147319     -2.08287e-05     3.18901e-05         0.515143        0.838038
                        0.350306         0.90976     -9.69194e-06     4.44168e-05          0.19752       -0.103201     -0.000101918     1.92146e-05
                     2.35674e-05    -3.56303e-05         0.515224        0.838545      1.97004e-05     9.43653e-05         0.176053       -0.021506
281800                  0.214368      -0.0578428     -5.42526e-05    -4.31772e-05         0.356279        0.907549      2.70336e-05     3.96499e-05
                     1.59845e-05    -4.31345e-05        0.0966903       -0.148466     -2.03378e-05     3.20124e-05         0.520703        0.834654
                        0.356264        0.907643     -8.94945e-06     4.45945e-05         0.196482       -0.103435     -0.000112012     1.96721e-05
                     2.25993e-05    -3.68006e-05         0.520773        0.835145      2.08752e-05     9.64615e-05         0.175886      -0.0214955
[End]