! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:33 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=140; L_y=90; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.027132        0.104088     -0.000692661    -0.000136279         0.334501       -0.936168     -0.000215523     0.000393413
                    -0.000774748    -0.000171613        -0.637247        0.234561     -0.000304692     0.000406542        -0.718028       -0.150579
                        0.334527       -0.936145     -0.000364045     0.000460088        0.0449978      -0.0976899     -2.32089e-05     0.000649853
                    -0.000245466     0.000449248           -0.718       -0.150639      3.08641e-05     0.000703528         0.489544        0.470706
281800                -0.0254206        0.102494     -0.000695172    -0.000132515         0.327394         -0.9389     -0.000213851     0.000394866
                    -0.000774903    -0.000168175        -0.636949         0.23974     -0.000299712     0.000410958        -0.718004        -0.14364
                         0.32742       -0.938879     -0.000360562     0.000465464        0.0438461       -0.096055     -1.66797e-05     0.000650606
                    -0.000243864     0.000451772        -0.717976       -0.143702      3.83427e-05     0.000704049         0.495917        0.466221
[End]