! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:39 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=130; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.15131       -0.221401      0.000583679    -0.000720931         0.906297         0.32586     -0.000236383     0.000154517
                     0.000493635    -0.000818444       -0.0215966       -0.217482     -0.000222946     0.000189124         0.714505         0.66416
                        0.906497        0.325894     -0.000364195    -7.55199e-06         0.257665      -0.0744484      0.000468351    -0.000747618
                    -0.000186204     8.45377e-05         0.714785        0.663912      0.000500696    -0.000758925         0.218606      0.00540201
281800                 -0.153892       -0.219369      0.000570984     -0.00071987         0.909405        0.317253     -0.000234322     0.000155922
                     0.000482202    -0.000818723       -0.0252642       -0.217816     -0.000218074     0.000193635         0.721097        0.656749
                        0.909607         0.31728     -0.000361889    -2.11839e-06         0.256963      -0.0761354       0.00045944    -0.000750884
                    -0.000184582      8.5904e-05         0.721376        0.656512      0.000491938    -0.000761972         0.219348      0.00457926
[End]