! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:02 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=130; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.520381        0.822851       0.00261514      5.0785e-05       -0.0965151        0.205284      0.000548959    -0.000464312
                      0.00263926     -1.7826e-06        -0.560578        0.820403     -3.88088e-06     0.000345259        -0.108421       0.0206995
                      -0.0964501        0.205718       -3.385e-05     0.000327782         0.965924       -0.123242     -0.000103335     0.000964216
                     0.000874564    -0.000487803         -0.10831       0.0205388      0.000109743      0.00105997         0.822493        0.557654
281800                  0.525597        0.819238       0.00261659     3.36721e-05       -0.0953079        0.207001      0.000545319     -0.00047494
                      0.00264095    -1.92245e-05        -0.556071        0.823487      1.89098e-06     0.000347014        -0.108091       0.0215404
                      -0.0952348        0.207426     -2.76459e-05     0.000328501         0.964469       -0.132368       -8.946e-05      0.00096784
                     0.000855058    -0.000505941        -0.107981       0.0213746      0.000121946      0.00105977          0.82831        0.549011
[End]