! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:02:07 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=200; L_x=130; L_y=90; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.165489       -0.110905      0.000406739    -0.000131742         0.450978        0.869822     -0.000130717    -3.08778e-05
                     0.000340326    -4.04272e-05        0.0596511       -0.174487     -3.19586e-05     0.000176807          0.58639         0.78857
                        0.451186        0.870012     -6.08501e-05     0.000222713         0.185995      -0.0713744      2.42827e-05    -0.000101863
                    -0.000133734    -2.02993e-05         0.586174        0.788986     -1.96297e-05    -8.55422e-05         0.184294     -0.00674115
281800                  0.163733       -0.112419      0.000401663    -0.000130471         0.456723        0.866958     -0.000129707    -2.98904e-05
                      0.00033692    -4.09297e-05        0.0574405       -0.175245     -3.02282e-05     0.000176908         0.591613        0.784648
                        0.456934        0.867148     -5.83874e-05     0.000222303           0.1853      -0.0715016      2.32303e-05    -0.000101697
                     -0.00013424    -2.06539e-05         0.591404        0.785069     -2.05474e-05    -8.55982e-05         0.184306     -0.00685758
[End]