! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:57:26 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=90; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  -0.59893        0.798571      -8.9034e-05     5.27275e-05       -0.0554067      0.00804248     -4.84487e-05     0.000136923
                    -0.000101663     5.09445e-05        -0.215312      -0.0624985      2.83489e-06     -0.00027209         0.789257       -0.571446
                      -0.0552911      0.00802086     -1.55748e-05    -0.000336022         0.801274        0.595379     -0.000102085    -0.000320573
                    -3.22765e-05     0.000131894         0.789271       -0.571438     -7.72681e-05    -0.000224927       0.00786578       -0.224031
281800                 -0.594941        0.801588     -9.02537e-05     5.25174e-05       -0.0547555      0.00837465     -4.69399e-05     0.000137863
                    -0.000102009     5.13263e-05         -0.21367      -0.0614444      4.19812e-07     -0.00027283         0.785232        -0.57769
                       -0.054642      0.00835199     -1.87043e-05    -0.000331925          0.80733        0.587198     -0.000103814    -0.000319286
                     -3.0752e-05     0.000132339         0.785247       -0.577681     -7.93308e-05    -0.000223277       0.00497262       -0.222242
[End]