! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:03:07 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=300; L_x=130; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.828132        0.517708     -5.94281e-05    -0.000376364         0.204643       0.0639948      -2.2531e-05     8.45368e-05
                    -5.97267e-05     -0.00036704         -0.95991       -0.265918     -0.000226135    -0.000184027       -0.0235416      -0.0830055
                        0.204721       0.0638159     -0.000159213    -0.000177741         0.385702        0.897221     -0.000906311    -0.000141681
                    -0.000146957    -4.33904e-06       -0.0235526      -0.0830028      -0.00124557    -0.000211642        -0.673311        0.733856
281800                 -0.826006        0.520998      -6.2803e-05    -0.000378327         0.205347       0.0624923     -2.10803e-05     8.62815e-05
                    -6.24906e-05    -0.000367032         -0.96139       -0.261303     -0.000230747    -0.000178242       -0.0237957       -0.080473
                        0.205426       0.0622987     -0.000159158    -0.000174675         0.395817         0.89275     -0.000903209    -0.000126135
                    -0.000150765    -2.10589e-06       -0.0237982      -0.0804779      -0.00124935    -0.000180325        -0.660448        0.745725
[End]