! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:54:27 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=70; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                0.00120686       0.0400589      0.000395339     8.12815e-05        -0.105245        0.993671     -9.85345e-05     -4.3663e-05
                      0.00037938     9.62001e-05        0.0578772        0.197769     -0.000110138    -7.64236e-05        -0.274451        0.939142
                       -0.105288        0.993576     -7.44093e-05    -3.34074e-05        0.0095659      -0.0389108      0.000294379     0.000138582
                    -0.000124357     -6.2293e-05        -0.274421        0.939204      0.000261226       6.333e-05         0.155261       -0.135517
281800                0.00165606       0.0381395      0.000396948     7.83329e-05       -0.0985125        0.994437     -9.78241e-05     -4.0752e-05
                     0.000380882     9.13875e-05        0.0593157        0.196095     -0.000111846    -7.60513e-05        -0.268474        0.941131
                       -0.098557        0.994342     -7.48136e-05    -3.39699e-05       0.00910035      -0.0370672      0.000294359     0.000137494
                    -0.000124158    -6.06422e-05        -0.268444        0.941189      0.000261813     6.19195e-05         0.153843       -0.135321
[End]