! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:56 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=400; L_x=120; L_y=110; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.214462       -0.134808      0.000716605     -8.5336e-05         0.640341        -0.72502     -0.000113096    -0.000417098
                     0.000710795    -2.63176e-05        -0.268979       -0.236149     -0.000113222    -0.000200379         0.397392        -0.84478
                        0.640435         -0.7249     -0.000132395    -0.000155214        -0.160237        -0.19606      0.000249702     0.000720797
                      -0.0001049    -0.000394565         0.397408       -0.844821      0.000217791     0.000768089        -0.353336      -0.0563733
281800                 -0.213071       -0.134857      0.000716792    -9.40724e-05         0.634381        -0.73063     -0.000120568    -0.000416865
                      0.00071127     -3.4398e-05        -0.268884        -0.23719     -0.000117414    -0.000200328         0.389243       -0.848305
                        0.634483       -0.730512     -0.000137679    -0.000153921        -0.163382       -0.191937      0.000256722     0.000722591
                    -0.000112086    -0.000393936         0.389258       -0.848345      0.000225262     0.000770564        -0.355072      -0.0488916
[End]