! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:57:02 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=90; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.636938         0.23318      0.000422869    -1.02159e-05        -0.717963       -0.154018      7.99972e-05    -0.000227044
                      0.00037116     9.27633e-06       -0.0271441        0.105409      4.43242e-05    -0.000272925         0.335849        -0.93549
                       -0.717976       -0.154024     -2.65306e-05    -0.000284653         0.485556        0.473731      3.33198e-06    -0.000382667
                     0.000196246    -0.000179927         0.335821       -0.935514      7.13025e-05    -0.000389612         0.046101      -0.0986345
281800                 -0.636666        0.238346      0.000420846    -1.25557e-05        -0.717965       -0.147075      7.68601e-05    -0.000225373
                     0.000369227     7.42473e-06       -0.0254236        0.103823       4.2926e-05    -0.000273148         0.328753       -0.938233
                       -0.717977        -0.14708     -2.75478e-05    -0.000282574         0.491969          0.4693      6.16763e-07    -0.000380745
                      0.00019393    -0.000182208         0.328726       -0.938255      6.49069e-05     -0.00038903         0.044941      -0.0970155
[End]