! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:58:32 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=500; L_x=100; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.105483        0.773036      0.000502178     0.000399073        -0.388302        0.489156      0.000208823     4.00678e-05
                     0.000434498     0.000380179        -0.060161       -0.100989     -0.000344878    -0.000975385        -0.181291       -0.976304
                       -0.388396        0.489331     -0.000337261    -0.000859295         0.776998      -0.0726109      -0.00092768     0.000101353
                     0.000120311    -9.77412e-05        -0.181383       -0.976192      -0.00105425     0.000100157       -0.0197656        0.115856
281800                  0.112104        0.771691      0.000503955     0.000394914        -0.384033        0.493161      0.000213936     3.77664e-05
                     0.000435072     0.000379603       -0.0614453       -0.103121      -0.00035488    -0.000970945        -0.189669        -0.97441
                       -0.384121        0.493336     -0.000348632    -0.000854491         0.775826      -0.0803514     -0.000924018     0.000108705
                     0.000121356    -9.81661e-05        -0.189758       -0.974294      -0.00105162     0.000111606       -0.0181503        0.118639
[End]