! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:58:46 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=100; L_y=180; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0798041      -0.0624812      0.000154054     0.000214824        0.0430414         0.99386     -2.49512e-05    -2.31485e-05
                     0.000251398     0.000218832        0.0347858        0.105917      4.97072e-05     0.000163191        -0.170851        0.978875
                       0.0428574         0.99394      7.14893e-06     6.43425e-05       -0.0740785       0.0691425      0.000251118    -0.000192656
                     6.44544e-05    -6.95929e-05        -0.170759         0.97897      0.000293794    -0.000174941        0.0685321      -0.0879268
281800                -0.0802062      -0.0642406      0.000156428     0.000211726        0.0499822        0.993391     -2.51915e-05    -2.25896e-05
                     0.000254375      0.00021662        0.0356489        0.104049      5.16081e-05     0.000163852        -0.164386        0.980151
                       0.0498005        0.993472      7.31017e-06     6.37489e-05       -0.0733274       0.0719627      0.000248788    -0.000194805
                     6.37266e-05    -6.92556e-05        -0.164294        0.980245      0.000292505    -0.000176428        0.0675682      -0.0867794
[End]