! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:55:14 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=80; L_y=100; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.158678      0.00991306     -0.000113834    -0.000309776        -0.173208        -0.97177     -0.000414677     3.59816e-05
                    -8.69144e-05    -0.000204981         0.145937        0.132433     -0.000370615    -7.45819e-05        0.0621207       -0.978417
                       -0.173247       -0.971941     -0.000406415    -9.59107e-06         0.145496      -0.0641199     -0.000146421     0.000252897
                    -0.000310173     5.12884e-05        0.0621317       -0.978361     -6.53676e-05     0.000186187         0.161499       -0.112954
281800                  0.158107      0.00734784     -0.000114369     -0.00031363        -0.180455        -0.97056     -0.000413584     3.98063e-05
                    -8.94031e-05    -0.000420985         0.146708        0.129996     -0.000371873    -6.98524e-05         0.055106       -0.979051
                       -0.180583       -0.970703     -0.000410248    -1.43914e-05         0.144927       -0.063702       -0.0001436     0.000254129
                    -0.000387797     8.13092e-05        0.0551177       -0.978995     -6.44455e-05     0.000187765         0.160355       -0.112751
[End]