! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:05 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=110; L_y=170; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0651394      -0.0497553       -7.583e-05    -0.000361298        0.0248736        0.996365      0.000606858     0.000117817
                      3.4878e-05    -0.000338155        0.0252661        0.078429      0.000541376     1.37897e-05        -0.139457        0.986836
                       0.0247763        0.996286      0.000609403    -9.99083e-07       -0.0625407       0.0529099     -0.000147624     0.000335612
                     0.000512425     0.000128739        -0.139501        0.986637     -0.000126583      0.00040351        0.0459689      -0.0683544
281800                -0.0654249      -0.0515638     -7.66219e-05     -0.00036498        0.0318064        0.996057      0.000609035     0.000113675
                     3.10247e-05     -0.00034338         0.025956       0.0765225      0.000545735     9.88091e-06        -0.132876        0.987876
                       0.0317114        0.995979      0.000610388    -5.72575e-06       -0.0619681        0.055599     -0.000144743      0.00033961
                     0.000514717      0.00012555        -0.132919        0.987677     -0.000122545       0.0004078        0.0452128      -0.0669414
[End]