! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:11:43 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=200; L_y=70; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                  0.054117        0.184281      0.000154157     0.000290444        -0.258145        0.946831     -0.000191772    -0.000142939
                     0.000284027     0.000220879       -0.0644543      -0.0429622     -0.000170387      5.4178e-05       0.00909306        0.997099
                        -0.25811        0.946738     -0.000235437    -5.28822e-05         0.140199       -0.131247      0.000109796    -0.000227133
                    -0.000234245    -2.27017e-05       0.00911756        0.996972       4.5617e-05    -0.000150913       -0.0636414       0.0441627
281800                 0.0554673        0.182584      0.000158506     0.000287483        -0.252085        0.948713     -0.000189643     -0.00013872
                     0.000290604     0.000215181       -0.0646723      -0.0447653     -0.000170829     5.95564e-05        0.0160314        0.996916
                       -0.252049        0.948617     -0.000235825    -5.06262e-05         0.138821       -0.130903      0.000106637    -0.000226063
                    -0.000233679    -1.81947e-05        0.0160592        0.996792      4.00497e-05    -0.000150307       -0.0631799       0.0468541
[End]