! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:11:01 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=190; L_y=140; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0526717       -0.043197      0.000633836     0.000155117        0.0317573        0.997605      -0.00047814     0.000301928
                     0.000650283     4.41851e-05        -0.200888       -0.144476     -0.000690405    -2.38214e-05         0.209148        0.946115
                       0.0318445        0.997266     -0.000598581    -4.66031e-06       -0.0497947        0.046515      0.000469571    -0.000431256
                    -0.000485806      0.00033479         0.209352        0.945965      0.000459833    -0.000519473        -0.121186        0.215793
281800                -0.0529396      -0.0450103       0.00063578     0.000150238        0.0386527        0.997268      -0.00047459      0.00030534
                     0.000648284     3.94005e-05        -0.202109       -0.145675     -0.000690574    -1.96674e-05         0.215793        0.944178
                        0.038746        0.996927     -0.000598605    -9.99887e-07       -0.0492725       0.0490293      0.000465382    -0.000434255
                    -0.000482413     0.000336385         0.215997        0.944025      0.000455058    -0.000522153        -0.118674         0.21911
[End]