! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:59:40 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=110; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.317966       0.0648967      0.000738182     -0.00072179         -0.91703        0.229425     -0.000240972     0.000290849
                     0.000843112     -0.00052437        -0.237114       -0.165695      -0.00015759     0.000260356         -0.92286       -0.255487
                       -0.917397        0.229125     -0.000239059       0.0003652         0.311194      -0.0922206     -0.000905306    -0.000901442
                    -0.000292634     0.000336867        -0.922477        -0.25491      -0.00086117    -0.000757005         0.288631      -0.0204367
281800                 -0.316561       0.0685396      0.000830487    -0.000789375        -0.914978        0.238319     -0.000242352     0.000299108
                     0.000839493     -0.00053158        -0.239104        -0.16302     -0.000154474     0.000263458        -0.925025       -0.247324
                       -0.915348        0.238022     -0.000300967     0.000299742         0.309904      -0.0943419     -0.000916438    -0.000895515
                    -0.000289825     0.000344082         -0.92464       -0.246805     -0.000872612    -0.000752692         0.288616      -0.0221659
[End]