! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:00:53 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=120; L_y=110; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 0.0411207        0.126603     -0.000112731     9.25353e-05         -0.19958         0.97073     -0.000361403    -9.73628e-05
                    -0.000155027     9.00147e-05        0.0346591        0.108306     -0.000354688    -3.44363e-05        -0.179928        0.977092
                        -0.19953        0.970664     -0.000346635    -4.33291e-05        0.0877197       -0.100167     -1.78636e-05    -4.29427e-05
                    -0.000351635    -0.000112434        -0.179913        0.977079      -7.0987e-06    -4.86252e-05        0.0709822       -0.088872
281800                 0.0421419        0.124773     -0.000113284     9.37482e-05         -0.19322         0.97221     -0.000362191    -9.44709e-05
                    -0.000156353     9.12624e-05        0.0355628        0.106444     -0.000355356     -3.2155e-05         -0.17348         0.97843
                       -0.193169        0.972137     -0.000346722    -4.09866e-05        0.0866351      -0.0992314     -1.93744e-05    -4.29969e-05
                    -0.000352191    -0.000110019        -0.173464        0.978414      -9.4495e-06    -4.88735e-05        0.0700061      -0.0877464
[End]