! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:05:30 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=100; L_x=150; L_y=150; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                -0.0548872      -0.0407493       0.00032419    -5.15354e-05        0.0190136        0.997484      9.86883e-05     2.71701e-05
                     0.000478639    -0.000197674       -0.0541502      -0.0397702      6.99335e-06     6.44592e-05        0.0176052        0.997747
                       0.0187439        0.997408      9.09238e-05     0.000121259       -0.0533031       0.0427796      0.000333307      3.7675e-05
                     4.70389e-05      0.00021295        0.0175487        0.997413      0.000333351      8.9564e-05       -0.0527239       0.0416671
281800                -0.0551184      -0.0425808      0.000324956    -5.39578e-05        0.0259294        0.997238      0.000100841      2.4084e-05
                     0.000490233    -0.000201712       -0.0543728      -0.0416056      7.39429e-06     6.42428e-05        0.0245233        0.997511
                       0.0256514        0.997171      9.15419e-05     0.000121261       -0.0528391       0.0453562      0.000339047     3.49731e-05
                     4.20615e-05     0.000221859        0.0244599        0.997182       0.00033475     8.63344e-05       -0.0522737       0.0442383
[End]