! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 21:57:34 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=90; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.208804       -0.250879     -0.000714752      5.0054e-05         0.871729       -0.364114     -0.000349874     0.000207004
                    -0.000717018    -0.000107403       -0.0256561       -0.232515     -0.000528145    -0.000315628        -0.771637       -0.591226
                        0.871889       -0.364295     -0.000589809    -0.000282991       -0.0317541       -0.324696     -0.000361847    -0.000138083
                    -0.000476049     0.000254711        -0.771912       -0.590908     -0.000599141    -1.12587e-05         0.231171      -0.0358812
281800                 -0.208384       -0.249987     -0.000716638     5.05094e-05         0.868014       -0.374085     -0.000353553     0.000210037
                    -0.000723283     -0.00010693       -0.0285372       -0.232202     -0.000572451    -0.000269958        -0.776396       -0.584946
                        0.868126       -0.374014      -0.00059418    -0.000278827       -0.0385522       -0.322956     -0.000367885    -0.000135455
                    -0.000477697     0.000259031        -0.776678        -0.58463     -0.000568545      3.3157e-05         0.231056      -0.0367678
[End]