! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Fri Oct 24 22:06:47 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=160; L_y=130; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 376.73 376.73 
[Number of Frequencies] 2
[Network Data]
281750                 -0.175248       -0.207871     -0.000301341     0.000617593         0.908477        0.316813      0.000234577     -0.00104494
                     -0.00013794     0.000597107        -0.222764        -0.18992      -0.00028378    -0.000854802         0.809851       -0.507733
                        0.908686        0.316807     -0.000330679     -0.00112174         0.266496      -0.0539314     -0.000172679     0.000333389
                     0.000314215     -0.00103001         0.810037       -0.507797     -0.000199981     0.000426492       -0.0738394       -0.282996
281800                  -0.17769       -0.205746     -0.000292124     0.000644504         0.911417        0.308287      0.000226405     -0.00105173
                    -0.000130472     0.000597329        -0.221644        -0.18991     -0.000293572    -0.000855396         0.804381       -0.516834
                        0.911631        0.308281     -0.000375019     -0.00110842          0.26609      -0.0557435     -0.000175548     0.000339686
                     0.000303951      -0.0010424         0.804574       -0.516909     -0.000200807     0.000430354       -0.0805608       -0.280258
[End]