! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Sat Oct 18 10:10:12 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=170; L_y=120; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 259.888 259.888 
[Number of Frequencies] 1
[Network Data]
461000                  0.662532       -0.582692      1.83886e-05    -0.000182407        0.0654479       -0.331862      0.000405576    -0.000189231
                     1.66761e-05    -0.000177766         0.712919        0.411695      0.000287354    -0.000194774        -0.447353       -0.119917
                       0.0654315       -0.331855      0.000281419    -0.000188124          0.38288        0.811584      0.000252301     0.000177963
                     0.000412573     -0.00018146        -0.447353       -0.119911      0.000233659     0.000186917        -0.825384       0.0927245
[End]