! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Sat Oct 18 10:10:53 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=180; L_y=190; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 259.888 259.888 
[Number of Frequencies] 1
[Network Data]
461000                -0.0251992       -0.640006      -0.00019919      0.00119376        -0.487782       -0.551687      -0.00030543     -0.00174808
                    -0.000208406      0.00119555         0.217857       -0.678869      8.00337e-05    -0.000986783        -0.226288       -0.635232
                       -0.487766       -0.551666      8.67973e-05    -0.000965351         0.645441       0.0963961      -0.00161403     0.000746631
                     -0.00031343     -0.00175894        -0.226293       -0.635239      -0.00162636     0.000775505         0.607415        0.380484
[End]