! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Sat Oct 18 10:06:21 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=100; L_y=90; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 259.888 259.888 
[Number of Frequencies] 1
[Network Data]
461000                 -0.411609       -0.726977      6.75992e-05     0.000368452        -0.456947       -0.181776       0.00033282    -9.18612e-06
                     0.000112732      0.00027611        -0.696107        0.377112     -0.000249738     4.57254e-05         0.330035       -0.469077
                       -0.456953        -0.18178      -0.00023622     4.16159e-05         0.776134       -0.339811     -0.000277255    -0.000467191
                     0.000368841    -4.84815e-06         0.329999       -0.469031     -0.000212502    -0.000429835         0.177489       -0.782697
[End]