! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Sat Oct 18 10:06:20 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=100; L_y=80; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 259.888 259.888 
[Number of Frequencies] 1
[Network Data]
461000                   0.16555       0.0104388      0.000341601     0.000743564        -0.100056       -0.977631      0.000436961    -0.000524287
                     0.000358852      0.00073052        -0.154913       -0.700335      0.000448157    -0.000654679        -0.559549       -0.345269
                       -0.100051       -0.977577      0.000399287    -0.000653242         0.162398      -0.0467256     -0.000467132     0.000111746
                     0.000463266    -0.000526565        -0.559561        -0.34528     -0.000487727     8.76846e-05          0.69149       -0.237232
[End]