! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Sat Oct 18 10:05:41 2025
! Project name: Teste_Macro_Metasurface_Nanopilar.cst
! Parameters = {H=600; L_x=85; L_y=160; Lambda=1064; Max_L=200; Min_L=70; PathPara=1; Phi=0; Step_L=10; Theta=0; p=520; phaseX=180; phaseY=0}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port Zmax ("") mode 1
! Touchstone port 2 = CST MWS port Zmax ("") mode 2
! Touchstone port 3 = CST MWS port Zmin ("") mode 1
! Touchstone port 4 = CST MWS port Zmin ("") mode 2
! S-Parameters are not renormalized. Each port impedance will be approximated by the real part at minimum frequency. The values are described via the [Reference] keyword.
! Default impedance is overridden by [Reference]
[Version] 2.0
# GHz S RI R 376.73
[Number of Ports] 4
[Reference]
376.73 376.73 259.888 259.888 
[Number of Frequencies] 1
[Network Data]
461000                  -0.35727       -0.285855      0.000176418      0.00107438        -0.502468        0.709702     -7.81526e-05    -0.000427879
                      0.00016862      0.00109276        -0.401713         0.44014      0.000537718    -0.000123144         0.202684       -0.759397
                       -0.502463        0.709719      0.000519632    -0.000110281        -0.396238       -0.247194     -0.000432064     0.000192642
                    -9.03416e-05      -0.0004302         0.202683       -0.759406      -0.00042428     0.000188322        -0.103759       -0.591316
[End]